// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/common/common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionState int32

const (
	ConnectionState_CONNECTION_STATE_UNSPECIFIED  ConnectionState = 0
	ConnectionState_CONNECTION_STATE_CONNECTED    ConnectionState = 1
	ConnectionState_CONNECTION_STATE_DISCONNECTED ConnectionState = 2
	ConnectionState_CONNECTION_STATE_RECONNECTING ConnectionState = 3
	ConnectionState_CONNECTION_STATE_ERROR        ConnectionState = 4
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_CONNECTED",
		2: "CONNECTION_STATE_DISCONNECTED",
		3: "CONNECTION_STATE_RECONNECTING",
		4: "CONNECTION_STATE_ERROR",
	}
	ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED":  0,
		"CONNECTION_STATE_CONNECTED":    1,
		"CONNECTION_STATE_DISCONNECTED": 2,
		"CONNECTION_STATE_RECONNECTING": 3,
		"CONNECTION_STATE_ERROR":        4,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_common_common_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_proto_v1_common_common_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{0}
}

type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_STRING      ColumnType = 1
	ColumnType_COLUMN_TYPE_NUMBER      ColumnType = 2
	ColumnType_COLUMN_TYPE_DATE        ColumnType = 3
	ColumnType_COLUMN_TYPE_BOOLEAN     ColumnType = 4
	ColumnType_COLUMN_TYPE_ENUM        ColumnType = 5
	ColumnType_COLUMN_TYPE_PROGRESS    ColumnType = 6
	ColumnType_COLUMN_TYPE_STATUS      ColumnType = 7
	ColumnType_COLUMN_TYPE_ARRAY       ColumnType = 8
	ColumnType_COLUMN_TYPE_OBJECT      ColumnType = 9
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_UNSPECIFIED",
		1: "COLUMN_TYPE_STRING",
		2: "COLUMN_TYPE_NUMBER",
		3: "COLUMN_TYPE_DATE",
		4: "COLUMN_TYPE_BOOLEAN",
		5: "COLUMN_TYPE_ENUM",
		6: "COLUMN_TYPE_PROGRESS",
		7: "COLUMN_TYPE_STATUS",
		8: "COLUMN_TYPE_ARRAY",
		9: "COLUMN_TYPE_OBJECT",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_STRING":      1,
		"COLUMN_TYPE_NUMBER":      2,
		"COLUMN_TYPE_DATE":        3,
		"COLUMN_TYPE_BOOLEAN":     4,
		"COLUMN_TYPE_ENUM":        5,
		"COLUMN_TYPE_PROGRESS":    6,
		"COLUMN_TYPE_STATUS":      7,
		"COLUMN_TYPE_ARRAY":       8,
		"COLUMN_TYPE_OBJECT":      9,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_common_common_proto_enumTypes[1].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_proto_v1_common_common_proto_enumTypes[1]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{1}
}

type ColumnAlignment int32

const (
	ColumnAlignment_COLUMN_ALIGNMENT_UNSPECIFIED ColumnAlignment = 0
	ColumnAlignment_COLUMN_ALIGNMENT_LEFT        ColumnAlignment = 1
	ColumnAlignment_COLUMN_ALIGNMENT_CENTER      ColumnAlignment = 2
	ColumnAlignment_COLUMN_ALIGNMENT_RIGHT       ColumnAlignment = 3
)

// Enum value maps for ColumnAlignment.
var (
	ColumnAlignment_name = map[int32]string{
		0: "COLUMN_ALIGNMENT_UNSPECIFIED",
		1: "COLUMN_ALIGNMENT_LEFT",
		2: "COLUMN_ALIGNMENT_CENTER",
		3: "COLUMN_ALIGNMENT_RIGHT",
	}
	ColumnAlignment_value = map[string]int32{
		"COLUMN_ALIGNMENT_UNSPECIFIED": 0,
		"COLUMN_ALIGNMENT_LEFT":        1,
		"COLUMN_ALIGNMENT_CENTER":      2,
		"COLUMN_ALIGNMENT_RIGHT":       3,
	}
)

func (x ColumnAlignment) Enum() *ColumnAlignment {
	p := new(ColumnAlignment)
	*p = x
	return p
}

func (x ColumnAlignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnAlignment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_common_common_proto_enumTypes[2].Descriptor()
}

func (ColumnAlignment) Type() protoreflect.EnumType {
	return &file_proto_v1_common_common_proto_enumTypes[2]
}

func (x ColumnAlignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnAlignment.Descriptor instead.
func (ColumnAlignment) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{2}
}

type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_GET         OperationType = 1
	OperationType_OPERATION_TYPE_LIST        OperationType = 2
	OperationType_OPERATION_TYPE_FIND        OperationType = 3
	OperationType_OPERATION_TYPE_CREATE      OperationType = 4
	OperationType_OPERATION_TYPE_UPDATE      OperationType = 5
	OperationType_OPERATION_TYPE_DELETE      OperationType = 6
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_GET",
		2: "OPERATION_TYPE_LIST",
		3: "OPERATION_TYPE_FIND",
		4: "OPERATION_TYPE_CREATE",
		5: "OPERATION_TYPE_UPDATE",
		6: "OPERATION_TYPE_DELETE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_GET":         1,
		"OPERATION_TYPE_LIST":        2,
		"OPERATION_TYPE_FIND":        3,
		"OPERATION_TYPE_CREATE":      4,
		"OPERATION_TYPE_UPDATE":      5,
		"OPERATION_TYPE_DELETE":      6,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_common_common_proto_enumTypes[3].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_v1_common_common_proto_enumTypes[3]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{3}
}

// Connection represents a configured connection to a backend system.
type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_proto_v1_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Connection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Connection) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Connection) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Connection) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConnectionStatus reports the health of a connection.
type ConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	State         ConnectionState        `protobuf:"varint,2,opt,name=state,proto3,enum=omniview.sdk.common.v1.ConnectionState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_proto_v1_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionStatus) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ConnectionStatus) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ConnectionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConnectionStatus) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ResourceMeta uniquely identifies a resource type within a plugin.
type ResourceMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Singular      string                 `protobuf:"bytes,4,opt,name=singular,proto3" json:"singular,omitempty"`
	Plural        string                 `protobuf:"bytes,5,opt,name=plural,proto3" json:"plural,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ShortNames    []string               `protobuf:"bytes,8,rep,name=short_names,json=shortNames,proto3" json:"short_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMeta) Reset() {
	*x = ResourceMeta{}
	mi := &file_proto_v1_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMeta) ProtoMessage() {}

func (x *ResourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMeta.ProtoReflect.Descriptor instead.
func (*ResourceMeta) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceMeta) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceMeta) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceMeta) GetSingular() string {
	if x != nil {
		return x.Singular
	}
	return ""
}

func (x *ResourceMeta) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *ResourceMeta) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResourceMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceMeta) GetShortNames() []string {
	if x != nil {
		return x.ShortNames
	}
	return nil
}

// ResourceGroup is a logical grouping of resource types for UI rendering.
type ResourceGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Resources     []*ResourceMeta        `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGroup) Reset() {
	*x = ResourceGroup{}
	mi := &file_proto_v1_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroup) ProtoMessage() {}

func (x *ResourceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroup.ProtoReflect.Descriptor instead.
func (*ResourceGroup) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceGroup) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ResourceGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceGroup) GetResources() []*ResourceMeta {
	if x != nil {
		return x.Resources
	}
	return nil
}

// ResourceDefinition provides UI rendering metadata for a resource type.
type ResourceDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Meta                *ResourceMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	IdAccessor          string                 `protobuf:"bytes,2,opt,name=id_accessor,json=idAccessor,proto3" json:"id_accessor,omitempty"`
	NamespaceAccessor   string                 `protobuf:"bytes,3,opt,name=namespace_accessor,json=namespaceAccessor,proto3" json:"namespace_accessor,omitempty"`
	MemoizerAccessor    string                 `protobuf:"bytes,4,opt,name=memoizer_accessor,json=memoizerAccessor,proto3" json:"memoizer_accessor,omitempty"`
	ColumnDefinitions   []*ColumnDefinition    `protobuf:"bytes,5,rep,name=column_definitions,json=columnDefinitions,proto3" json:"column_definitions,omitempty"`
	SupportedOperations []OperationType        `protobuf:"varint,6,rep,packed,name=supported_operations,json=supportedOperations,proto3,enum=omniview.sdk.common.v1.OperationType" json:"supported_operations,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	mi := &file_proto_v1_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDefinition.ProtoReflect.Descriptor instead.
func (*ResourceDefinition) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceDefinition) GetMeta() *ResourceMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ResourceDefinition) GetIdAccessor() string {
	if x != nil {
		return x.IdAccessor
	}
	return ""
}

func (x *ResourceDefinition) GetNamespaceAccessor() string {
	if x != nil {
		return x.NamespaceAccessor
	}
	return ""
}

func (x *ResourceDefinition) GetMemoizerAccessor() string {
	if x != nil {
		return x.MemoizerAccessor
	}
	return ""
}

func (x *ResourceDefinition) GetColumnDefinitions() []*ColumnDefinition {
	if x != nil {
		return x.ColumnDefinitions
	}
	return nil
}

func (x *ResourceDefinition) GetSupportedOperations() []OperationType {
	if x != nil {
		return x.SupportedOperations
	}
	return nil
}

// ColumnDefinition describes a table column for UI rendering.
type ColumnDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Header        string                 `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Accessors     []string               `protobuf:"bytes,3,rep,name=accessors,proto3" json:"accessors,omitempty"`
	Type          ColumnType             `protobuf:"varint,4,opt,name=type,proto3,enum=omniview.sdk.common.v1.ColumnType" json:"type,omitempty"`
	Alignment     ColumnAlignment        `protobuf:"varint,5,opt,name=alignment,proto3,enum=omniview.sdk.common.v1.ColumnAlignment" json:"alignment,omitempty"`
	Width         int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Formatter     string                 `protobuf:"bytes,7,opt,name=formatter,proto3" json:"formatter,omitempty"`
	ResourceLink  *ResourceLink          `protobuf:"bytes,8,opt,name=resource_link,json=resourceLink,proto3" json:"resource_link,omitempty"`
	Sortable      bool                   `protobuf:"varint,9,opt,name=sortable,proto3" json:"sortable,omitempty"`
	Hidden        bool                   `protobuf:"varint,10,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnDefinition) Reset() {
	*x = ColumnDefinition{}
	mi := &file_proto_v1_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDefinition) ProtoMessage() {}

func (x *ColumnDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDefinition.ProtoReflect.Descriptor instead.
func (*ColumnDefinition) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *ColumnDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColumnDefinition) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ColumnDefinition) GetAccessors() []string {
	if x != nil {
		return x.Accessors
	}
	return nil
}

func (x *ColumnDefinition) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *ColumnDefinition) GetAlignment() ColumnAlignment {
	if x != nil {
		return x.Alignment
	}
	return ColumnAlignment_COLUMN_ALIGNMENT_UNSPECIFIED
}

func (x *ColumnDefinition) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ColumnDefinition) GetFormatter() string {
	if x != nil {
		return x.Formatter
	}
	return ""
}

func (x *ColumnDefinition) GetResourceLink() *ResourceLink {
	if x != nil {
		return x.ResourceLink
	}
	return nil
}

func (x *ColumnDefinition) GetSortable() bool {
	if x != nil {
		return x.Sortable
	}
	return false
}

func (x *ColumnDefinition) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// ResourceLink connects a column value to another resource type for navigation.
type ResourceLink struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdAccessor        string                 `protobuf:"bytes,1,opt,name=id_accessor,json=idAccessor,proto3" json:"id_accessor,omitempty"`
	NamespaceAccessor string                 `protobuf:"bytes,2,opt,name=namespace_accessor,json=namespaceAccessor,proto3" json:"namespace_accessor,omitempty"`
	Namespaced        bool                   `protobuf:"varint,3,opt,name=namespaced,proto3" json:"namespaced,omitempty"`
	Key               string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	KeyAccessor       string                 `protobuf:"bytes,5,opt,name=key_accessor,json=keyAccessor,proto3" json:"key_accessor,omitempty"`
	KeyMap            map[string]string      `protobuf:"bytes,6,rep,name=key_map,json=keyMap,proto3" json:"key_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DetailExtractors  map[string]string      `protobuf:"bytes,7,rep,name=detail_extractors,json=detailExtractors,proto3" json:"detail_extractors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DisplayId         string                 `protobuf:"bytes,8,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceLink) Reset() {
	*x = ResourceLink{}
	mi := &file_proto_v1_common_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLink) ProtoMessage() {}

func (x *ResourceLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLink.ProtoReflect.Descriptor instead.
func (*ResourceLink) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceLink) GetIdAccessor() string {
	if x != nil {
		return x.IdAccessor
	}
	return ""
}

func (x *ResourceLink) GetNamespaceAccessor() string {
	if x != nil {
		return x.NamespaceAccessor
	}
	return ""
}

func (x *ResourceLink) GetNamespaced() bool {
	if x != nil {
		return x.Namespaced
	}
	return false
}

func (x *ResourceLink) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResourceLink) GetKeyAccessor() string {
	if x != nil {
		return x.KeyAccessor
	}
	return ""
}

func (x *ResourceLink) GetKeyMap() map[string]string {
	if x != nil {
		return x.KeyMap
	}
	return nil
}

func (x *ResourceLink) GetDetailExtractors() map[string]string {
	if x != nil {
		return x.DetailExtractors
	}
	return nil
}

func (x *ResourceLink) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

// ResourceError is a structured error for resource operations.
type ResourceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceError) Reset() {
	*x = ResourceError{}
	mi := &file_proto_v1_common_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceError) ProtoMessage() {}

func (x *ResourceError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceError.ProtoReflect.Descriptor instead.
func (*ResourceError) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResourceError) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceError) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *ResourceError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// EditorSchema provides Monaco editor validation for a resource type.
type EditorSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	FileMatch     []string               `protobuf:"bytes,2,rep,name=file_match,json=fileMatch,proto3" json:"file_match,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Schema        []byte                 `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditorSchema) Reset() {
	*x = EditorSchema{}
	mi := &file_proto_v1_common_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSchema) ProtoMessage() {}

func (x *EditorSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSchema.ProtoReflect.Descriptor instead.
func (*EditorSchema) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *EditorSchema) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *EditorSchema) GetFileMatch() []string {
	if x != nil {
		return x.FileMatch
	}
	return nil
}

func (x *EditorSchema) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *EditorSchema) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_proto_v1_common_common_proto protoreflect.FileDescriptor

const file_proto_v1_common_common_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/common/common.proto\x12\x16omniview.sdk.common.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x02\n" +
	"\n" +
	"Connection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12F\n" +
	"\x06labels\x18\x05 \x03(\v2..omniview.sdk.common.v1.Connection.LabelsEntryR\x06labels\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x10ConnectionStatus\x12B\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\".omniview.sdk.common.v1.ConnectionR\n" +
	"connection\x12=\n" +
	"\x05state\x18\x02 \x01(\x0e2'.omniview.sdk.common.v1.ConnectionStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xec\x01\n" +
	"\fResourceMeta\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\bsingular\x18\x04 \x01(\tR\bsingular\x12\x16\n" +
	"\x06plural\x18\x05 \x01(\tR\x06plural\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1f\n" +
	"\vshort_names\x18\b \x03(\tR\n" +
	"shortNames\"\xad\x01\n" +
	"\rResourceGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12B\n" +
	"\tresources\x18\x05 \x03(\v2$.omniview.sdk.common.v1.ResourceMetaR\tresources\"\xfe\x02\n" +
	"\x12ResourceDefinition\x128\n" +
	"\x04meta\x18\x01 \x01(\v2$.omniview.sdk.common.v1.ResourceMetaR\x04meta\x12\x1f\n" +
	"\vid_accessor\x18\x02 \x01(\tR\n" +
	"idAccessor\x12-\n" +
	"\x12namespace_accessor\x18\x03 \x01(\tR\x11namespaceAccessor\x12+\n" +
	"\x11memoizer_accessor\x18\x04 \x01(\tR\x10memoizerAccessor\x12W\n" +
	"\x12column_definitions\x18\x05 \x03(\v2(.omniview.sdk.common.v1.ColumnDefinitionR\x11columnDefinitions\x12X\n" +
	"\x14supported_operations\x18\x06 \x03(\x0e2%.omniview.sdk.common.v1.OperationTypeR\x13supportedOperations\"\x8a\x03\n" +
	"\x10ColumnDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06header\x18\x02 \x01(\tR\x06header\x12\x1c\n" +
	"\taccessors\x18\x03 \x03(\tR\taccessors\x126\n" +
	"\x04type\x18\x04 \x01(\x0e2\".omniview.sdk.common.v1.ColumnTypeR\x04type\x12E\n" +
	"\talignment\x18\x05 \x01(\x0e2'.omniview.sdk.common.v1.ColumnAlignmentR\talignment\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x1c\n" +
	"\tformatter\x18\a \x01(\tR\tformatter\x12I\n" +
	"\rresource_link\x18\b \x01(\v2$.omniview.sdk.common.v1.ResourceLinkR\fresourceLink\x12\x1a\n" +
	"\bsortable\x18\t \x01(\bR\bsortable\x12\x16\n" +
	"\x06hidden\x18\n" +
	" \x01(\bR\x06hidden\"\x86\x04\n" +
	"\fResourceLink\x12\x1f\n" +
	"\vid_accessor\x18\x01 \x01(\tR\n" +
	"idAccessor\x12-\n" +
	"\x12namespace_accessor\x18\x02 \x01(\tR\x11namespaceAccessor\x12\x1e\n" +
	"\n" +
	"namespaced\x18\x03 \x01(\bR\n" +
	"namespaced\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12!\n" +
	"\fkey_accessor\x18\x05 \x01(\tR\vkeyAccessor\x12I\n" +
	"\akey_map\x18\x06 \x03(\v20.omniview.sdk.common.v1.ResourceLink.KeyMapEntryR\x06keyMap\x12g\n" +
	"\x11detail_extractors\x18\a \x03(\v2:.omniview.sdk.common.v1.ResourceLink.DetailExtractorsEntryR\x10detailExtractors\x12\x1d\n" +
	"\n" +
	"display_id\x18\b \x01(\tR\tdisplayId\x1a9\n" +
	"\vKeyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15DetailExtractorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\rResourceError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x121\n" +
	"\adetails\x18\x05 \x01(\v2\x17.google.protobuf.StructR\adetails\"s\n" +
	"\fEditorSchema\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"file_match\x18\x02 \x03(\tR\tfileMatch\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\fR\x06schema*\xb5\x01\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONNECTION_STATE_CONNECTED\x10\x01\x12!\n" +
	"\x1dCONNECTION_STATE_DISCONNECTED\x10\x02\x12!\n" +
	"\x1dCONNECTION_STATE_RECONNECTING\x10\x03\x12\x1a\n" +
	"\x16CONNECTION_STATE_ERROR\x10\x04*\xff\x01\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COLUMN_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12COLUMN_TYPE_NUMBER\x10\x02\x12\x14\n" +
	"\x10COLUMN_TYPE_DATE\x10\x03\x12\x17\n" +
	"\x13COLUMN_TYPE_BOOLEAN\x10\x04\x12\x14\n" +
	"\x10COLUMN_TYPE_ENUM\x10\x05\x12\x18\n" +
	"\x14COLUMN_TYPE_PROGRESS\x10\x06\x12\x16\n" +
	"\x12COLUMN_TYPE_STATUS\x10\a\x12\x15\n" +
	"\x11COLUMN_TYPE_ARRAY\x10\b\x12\x16\n" +
	"\x12COLUMN_TYPE_OBJECT\x10\t*\x87\x01\n" +
	"\x0fColumnAlignment\x12 \n" +
	"\x1cCOLUMN_ALIGNMENT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COLUMN_ALIGNMENT_LEFT\x10\x01\x12\x1b\n" +
	"\x17COLUMN_ALIGNMENT_CENTER\x10\x02\x12\x1a\n" +
	"\x16COLUMN_ALIGNMENT_RIGHT\x10\x03*\xca\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OPERATION_TYPE_GET\x10\x01\x12\x17\n" +
	"\x13OPERATION_TYPE_LIST\x10\x02\x12\x17\n" +
	"\x13OPERATION_TYPE_FIND\x10\x03\x12\x19\n" +
	"\x15OPERATION_TYPE_CREATE\x10\x04\x12\x19\n" +
	"\x15OPERATION_TYPE_UPDATE\x10\x05\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\x06B<Z:github.com/omniviewdev/plugin-sdk/proto/v1/common;commonpbb\x06proto3"

var (
	file_proto_v1_common_common_proto_rawDescOnce sync.Once
	file_proto_v1_common_common_proto_rawDescData []byte
)

func file_proto_v1_common_common_proto_rawDescGZIP() []byte {
	file_proto_v1_common_common_proto_rawDescOnce.Do(func() {
		file_proto_v1_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_common_common_proto_rawDesc), len(file_proto_v1_common_common_proto_rawDesc)))
	})
	return file_proto_v1_common_common_proto_rawDescData
}

var file_proto_v1_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_v1_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_v1_common_common_proto_goTypes = []any{
	(ConnectionState)(0),       // 0: omniview.sdk.common.v1.ConnectionState
	(ColumnType)(0),            // 1: omniview.sdk.common.v1.ColumnType
	(ColumnAlignment)(0),       // 2: omniview.sdk.common.v1.ColumnAlignment
	(OperationType)(0),         // 3: omniview.sdk.common.v1.OperationType
	(*Connection)(nil),         // 4: omniview.sdk.common.v1.Connection
	(*ConnectionStatus)(nil),   // 5: omniview.sdk.common.v1.ConnectionStatus
	(*ResourceMeta)(nil),       // 6: omniview.sdk.common.v1.ResourceMeta
	(*ResourceGroup)(nil),      // 7: omniview.sdk.common.v1.ResourceGroup
	(*ResourceDefinition)(nil), // 8: omniview.sdk.common.v1.ResourceDefinition
	(*ColumnDefinition)(nil),   // 9: omniview.sdk.common.v1.ColumnDefinition
	(*ResourceLink)(nil),       // 10: omniview.sdk.common.v1.ResourceLink
	(*ResourceError)(nil),      // 11: omniview.sdk.common.v1.ResourceError
	(*EditorSchema)(nil),       // 12: omniview.sdk.common.v1.EditorSchema
	nil,                        // 13: omniview.sdk.common.v1.Connection.LabelsEntry
	nil,                        // 14: omniview.sdk.common.v1.ResourceLink.KeyMapEntry
	nil,                        // 15: omniview.sdk.common.v1.ResourceLink.DetailExtractorsEntry
	(*structpb.Struct)(nil),    // 16: google.protobuf.Struct
}
var file_proto_v1_common_common_proto_depIdxs = []int32{
	13, // 0: omniview.sdk.common.v1.Connection.labels:type_name -> omniview.sdk.common.v1.Connection.LabelsEntry
	16, // 1: omniview.sdk.common.v1.Connection.data:type_name -> google.protobuf.Struct
	4,  // 2: omniview.sdk.common.v1.ConnectionStatus.connection:type_name -> omniview.sdk.common.v1.Connection
	0,  // 3: omniview.sdk.common.v1.ConnectionStatus.state:type_name -> omniview.sdk.common.v1.ConnectionState
	16, // 4: omniview.sdk.common.v1.ConnectionStatus.metadata:type_name -> google.protobuf.Struct
	6,  // 5: omniview.sdk.common.v1.ResourceGroup.resources:type_name -> omniview.sdk.common.v1.ResourceMeta
	6,  // 6: omniview.sdk.common.v1.ResourceDefinition.meta:type_name -> omniview.sdk.common.v1.ResourceMeta
	9,  // 7: omniview.sdk.common.v1.ResourceDefinition.column_definitions:type_name -> omniview.sdk.common.v1.ColumnDefinition
	3,  // 8: omniview.sdk.common.v1.ResourceDefinition.supported_operations:type_name -> omniview.sdk.common.v1.OperationType
	1,  // 9: omniview.sdk.common.v1.ColumnDefinition.type:type_name -> omniview.sdk.common.v1.ColumnType
	2,  // 10: omniview.sdk.common.v1.ColumnDefinition.alignment:type_name -> omniview.sdk.common.v1.ColumnAlignment
	10, // 11: omniview.sdk.common.v1.ColumnDefinition.resource_link:type_name -> omniview.sdk.common.v1.ResourceLink
	14, // 12: omniview.sdk.common.v1.ResourceLink.key_map:type_name -> omniview.sdk.common.v1.ResourceLink.KeyMapEntry
	15, // 13: omniview.sdk.common.v1.ResourceLink.detail_extractors:type_name -> omniview.sdk.common.v1.ResourceLink.DetailExtractorsEntry
	16, // 14: omniview.sdk.common.v1.ResourceError.details:type_name -> google.protobuf.Struct
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_v1_common_common_proto_init() }
func file_proto_v1_common_common_proto_init() {
	if File_proto_v1_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_common_common_proto_rawDesc), len(file_proto_v1_common_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_common_common_proto_goTypes,
		DependencyIndexes: file_proto_v1_common_common_proto_depIdxs,
		EnumInfos:         file_proto_v1_common_common_proto_enumTypes,
		MessageInfos:      file_proto_v1_common_common_proto_msgTypes,
	}.Build()
	File_proto_v1_common_common_proto = out.File
	file_proto_v1_common_common_proto_goTypes = nil
	file_proto_v1_common_common_proto_depIdxs = nil
}
