// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/resource/filter.proto

package resourcepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterOperator int32

const (
	FilterOperator_FILTER_OP_UNSPECIFIED FilterOperator = 0
	FilterOperator_FILTER_OP_EQ          FilterOperator = 1
	FilterOperator_FILTER_OP_NEQ         FilterOperator = 2
	FilterOperator_FILTER_OP_GT          FilterOperator = 3
	FilterOperator_FILTER_OP_GTE         FilterOperator = 4
	FilterOperator_FILTER_OP_LT          FilterOperator = 5
	FilterOperator_FILTER_OP_LTE         FilterOperator = 6
	FilterOperator_FILTER_OP_CONTAINS    FilterOperator = 7
	FilterOperator_FILTER_OP_PREFIX      FilterOperator = 8
	FilterOperator_FILTER_OP_SUFFIX      FilterOperator = 9
	FilterOperator_FILTER_OP_REGEX       FilterOperator = 10
	FilterOperator_FILTER_OP_IN          FilterOperator = 11
	FilterOperator_FILTER_OP_NOT_IN      FilterOperator = 12
	FilterOperator_FILTER_OP_EXISTS      FilterOperator = 13
	FilterOperator_FILTER_OP_NOT_EXISTS  FilterOperator = 14
	FilterOperator_FILTER_OP_HAS_KEY     FilterOperator = 15
)

// Enum value maps for FilterOperator.
var (
	FilterOperator_name = map[int32]string{
		0:  "FILTER_OP_UNSPECIFIED",
		1:  "FILTER_OP_EQ",
		2:  "FILTER_OP_NEQ",
		3:  "FILTER_OP_GT",
		4:  "FILTER_OP_GTE",
		5:  "FILTER_OP_LT",
		6:  "FILTER_OP_LTE",
		7:  "FILTER_OP_CONTAINS",
		8:  "FILTER_OP_PREFIX",
		9:  "FILTER_OP_SUFFIX",
		10: "FILTER_OP_REGEX",
		11: "FILTER_OP_IN",
		12: "FILTER_OP_NOT_IN",
		13: "FILTER_OP_EXISTS",
		14: "FILTER_OP_NOT_EXISTS",
		15: "FILTER_OP_HAS_KEY",
	}
	FilterOperator_value = map[string]int32{
		"FILTER_OP_UNSPECIFIED": 0,
		"FILTER_OP_EQ":          1,
		"FILTER_OP_NEQ":         2,
		"FILTER_OP_GT":          3,
		"FILTER_OP_GTE":         4,
		"FILTER_OP_LT":          5,
		"FILTER_OP_LTE":         6,
		"FILTER_OP_CONTAINS":    7,
		"FILTER_OP_PREFIX":      8,
		"FILTER_OP_SUFFIX":      9,
		"FILTER_OP_REGEX":       10,
		"FILTER_OP_IN":          11,
		"FILTER_OP_NOT_IN":      12,
		"FILTER_OP_EXISTS":      13,
		"FILTER_OP_NOT_EXISTS":  14,
		"FILTER_OP_HAS_KEY":     15,
	}
)

func (x FilterOperator) Enum() *FilterOperator {
	p := new(FilterOperator)
	*p = x
	return p
}

func (x FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_filter_proto_enumTypes[0].Descriptor()
}

func (FilterOperator) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_filter_proto_enumTypes[0]
}

func (x FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperator.Descriptor instead.
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{0}
}

type FilterFieldType int32

const (
	FilterFieldType_FILTER_FIELD_TYPE_UNSPECIFIED FilterFieldType = 0
	FilterFieldType_FILTER_FIELD_TYPE_STRING      FilterFieldType = 1
	FilterFieldType_FILTER_FIELD_TYPE_INTEGER     FilterFieldType = 2
	FilterFieldType_FILTER_FIELD_TYPE_NUMBER      FilterFieldType = 3
	FilterFieldType_FILTER_FIELD_TYPE_BOOLEAN     FilterFieldType = 4
	FilterFieldType_FILTER_FIELD_TYPE_DATETIME    FilterFieldType = 5
	FilterFieldType_FILTER_FIELD_TYPE_ENUM        FilterFieldType = 6
	FilterFieldType_FILTER_FIELD_TYPE_MAP         FilterFieldType = 7
)

// Enum value maps for FilterFieldType.
var (
	FilterFieldType_name = map[int32]string{
		0: "FILTER_FIELD_TYPE_UNSPECIFIED",
		1: "FILTER_FIELD_TYPE_STRING",
		2: "FILTER_FIELD_TYPE_INTEGER",
		3: "FILTER_FIELD_TYPE_NUMBER",
		4: "FILTER_FIELD_TYPE_BOOLEAN",
		5: "FILTER_FIELD_TYPE_DATETIME",
		6: "FILTER_FIELD_TYPE_ENUM",
		7: "FILTER_FIELD_TYPE_MAP",
	}
	FilterFieldType_value = map[string]int32{
		"FILTER_FIELD_TYPE_UNSPECIFIED": 0,
		"FILTER_FIELD_TYPE_STRING":      1,
		"FILTER_FIELD_TYPE_INTEGER":     2,
		"FILTER_FIELD_TYPE_NUMBER":      3,
		"FILTER_FIELD_TYPE_BOOLEAN":     4,
		"FILTER_FIELD_TYPE_DATETIME":    5,
		"FILTER_FIELD_TYPE_ENUM":        6,
		"FILTER_FIELD_TYPE_MAP":         7,
	}
)

func (x FilterFieldType) Enum() *FilterFieldType {
	p := new(FilterFieldType)
	*p = x
	return p
}

func (x FilterFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_filter_proto_enumTypes[1].Descriptor()
}

func (FilterFieldType) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_filter_proto_enumTypes[1]
}

func (x FilterFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterFieldType.Descriptor instead.
func (FilterFieldType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{1}
}

type FilterLogic int32

const (
	FilterLogic_FILTER_LOGIC_UNSPECIFIED FilterLogic = 0
	FilterLogic_FILTER_LOGIC_AND         FilterLogic = 1
	FilterLogic_FILTER_LOGIC_OR          FilterLogic = 2
)

// Enum value maps for FilterLogic.
var (
	FilterLogic_name = map[int32]string{
		0: "FILTER_LOGIC_UNSPECIFIED",
		1: "FILTER_LOGIC_AND",
		2: "FILTER_LOGIC_OR",
	}
	FilterLogic_value = map[string]int32{
		"FILTER_LOGIC_UNSPECIFIED": 0,
		"FILTER_LOGIC_AND":         1,
		"FILTER_LOGIC_OR":          2,
	}
)

func (x FilterLogic) Enum() *FilterLogic {
	p := new(FilterLogic)
	*p = x
	return p
}

func (x FilterLogic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterLogic) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_filter_proto_enumTypes[2].Descriptor()
}

func (FilterLogic) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_filter_proto_enumTypes[2]
}

func (x FilterLogic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterLogic.Descriptor instead.
func (FilterLogic) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{2}
}

// FilterField declares a filterable field for introspection.
type FilterField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          FilterFieldType        `protobuf:"varint,4,opt,name=type,proto3,enum=omniview.sdk.resource.v1.FilterFieldType" json:"type,omitempty"`
	Operators     []FilterOperator       `protobuf:"varint,5,rep,packed,name=operators,proto3,enum=omniview.sdk.resource.v1.FilterOperator" json:"operators,omitempty"`
	AllowedValues []string               `protobuf:"bytes,6,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	Required      bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterField) Reset() {
	*x = FilterField{}
	mi := &file_proto_v1_resource_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterField) ProtoMessage() {}

func (x *FilterField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterField.ProtoReflect.Descriptor instead.
func (*FilterField) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterField) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilterField) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *FilterField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FilterField) GetType() FilterFieldType {
	if x != nil {
		return x.Type
	}
	return FilterFieldType_FILTER_FIELD_TYPE_UNSPECIFIED
}

func (x *FilterField) GetOperators() []FilterOperator {
	if x != nil {
		return x.Operators
	}
	return nil
}

func (x *FilterField) GetAllowedValues() []string {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

func (x *FilterField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// FilterPredicate is a single condition in a query.
type FilterPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      FilterOperator         `protobuf:"varint,2,opt,name=operator,proto3,enum=omniview.sdk.resource.v1.FilterOperator" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterPredicate) Reset() {
	*x = FilterPredicate{}
	mi := &file_proto_v1_resource_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterPredicate) ProtoMessage() {}

func (x *FilterPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterPredicate.ProtoReflect.Descriptor instead.
func (*FilterPredicate) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FilterPredicate) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterPredicate) GetOperator() FilterOperator {
	if x != nil {
		return x.Operator
	}
	return FilterOperator_FILTER_OP_UNSPECIFIED
}

func (x *FilterPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// FilterExpression combines predicates with a logical operator.
// Supports one level of nesting (AND of ORs, or OR of ANDs).
type FilterExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logic         FilterLogic            `protobuf:"varint,1,opt,name=logic,proto3,enum=omniview.sdk.resource.v1.FilterLogic" json:"logic,omitempty"`
	Predicates    []*FilterPredicate     `protobuf:"bytes,2,rep,name=predicates,proto3" json:"predicates,omitempty"`
	Groups        []*FilterExpression    `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpression) Reset() {
	*x = FilterExpression{}
	mi := &file_proto_v1_resource_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpression) ProtoMessage() {}

func (x *FilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpression.ProtoReflect.Descriptor instead.
func (*FilterExpression) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{2}
}

func (x *FilterExpression) GetLogic() FilterLogic {
	if x != nil {
		return x.Logic
	}
	return FilterLogic_FILTER_LOGIC_UNSPECIFIED
}

func (x *FilterExpression) GetPredicates() []*FilterPredicate {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *FilterExpression) GetGroups() []*FilterExpression {
	if x != nil {
		return x.Groups
	}
	return nil
}

// OrderField specifies a sort field.
type OrderField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderField) Reset() {
	*x = OrderField{}
	mi := &file_proto_v1_resource_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderField) ProtoMessage() {}

func (x *OrderField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderField.ProtoReflect.Descriptor instead.
func (*OrderField) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{3}
}

func (x *OrderField) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OrderField) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

// PaginationParams supports both page-based and cursor-based pagination.
type PaginationParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationParams) Reset() {
	*x = PaginationParams{}
	mi := &file_proto_v1_resource_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationParams) ProtoMessage() {}

func (x *PaginationParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationParams.ProtoReflect.Descriptor instead.
func (*PaginationParams) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_filter_proto_rawDescGZIP(), []int{4}
}

func (x *PaginationParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationParams) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationParams) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

var File_proto_v1_resource_filter_proto protoreflect.FileDescriptor

const file_proto_v1_resource_filter_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/v1/resource/filter.proto\x12\x18omniview.sdk.resource.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb0\x02\n" +
	"\vFilterField\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12=\n" +
	"\x04type\x18\x04 \x01(\x0e2).omniview.sdk.resource.v1.FilterFieldTypeR\x04type\x12F\n" +
	"\toperators\x18\x05 \x03(\x0e2(.omniview.sdk.resource.v1.FilterOperatorR\toperators\x12%\n" +
	"\x0eallowed_values\x18\x06 \x03(\tR\rallowedValues\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\"\x9b\x01\n" +
	"\x0fFilterPredicate\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12D\n" +
	"\boperator\x18\x02 \x01(\x0e2(.omniview.sdk.resource.v1.FilterOperatorR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xde\x01\n" +
	"\x10FilterExpression\x12;\n" +
	"\x05logic\x18\x01 \x01(\x0e2%.omniview.sdk.resource.v1.FilterLogicR\x05logic\x12I\n" +
	"\n" +
	"predicates\x18\x02 \x03(\v2).omniview.sdk.resource.v1.FilterPredicateR\n" +
	"predicates\x12B\n" +
	"\x06groups\x18\x03 \x03(\v2*.omniview.sdk.resource.v1.FilterExpressionR\x06groups\"@\n" +
	"\n" +
	"OrderField\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\"[\n" +
	"\x10PaginationParams\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor*\xe2\x02\n" +
	"\x0eFilterOperator\x12\x19\n" +
	"\x15FILTER_OP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFILTER_OP_EQ\x10\x01\x12\x11\n" +
	"\rFILTER_OP_NEQ\x10\x02\x12\x10\n" +
	"\fFILTER_OP_GT\x10\x03\x12\x11\n" +
	"\rFILTER_OP_GTE\x10\x04\x12\x10\n" +
	"\fFILTER_OP_LT\x10\x05\x12\x11\n" +
	"\rFILTER_OP_LTE\x10\x06\x12\x16\n" +
	"\x12FILTER_OP_CONTAINS\x10\a\x12\x14\n" +
	"\x10FILTER_OP_PREFIX\x10\b\x12\x14\n" +
	"\x10FILTER_OP_SUFFIX\x10\t\x12\x13\n" +
	"\x0fFILTER_OP_REGEX\x10\n" +
	"\x12\x10\n" +
	"\fFILTER_OP_IN\x10\v\x12\x14\n" +
	"\x10FILTER_OP_NOT_IN\x10\f\x12\x14\n" +
	"\x10FILTER_OP_EXISTS\x10\r\x12\x18\n" +
	"\x14FILTER_OP_NOT_EXISTS\x10\x0e\x12\x15\n" +
	"\x11FILTER_OP_HAS_KEY\x10\x0f*\x85\x02\n" +
	"\x0fFilterFieldType\x12!\n" +
	"\x1dFILTER_FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FILTER_FIELD_TYPE_STRING\x10\x01\x12\x1d\n" +
	"\x19FILTER_FIELD_TYPE_INTEGER\x10\x02\x12\x1c\n" +
	"\x18FILTER_FIELD_TYPE_NUMBER\x10\x03\x12\x1d\n" +
	"\x19FILTER_FIELD_TYPE_BOOLEAN\x10\x04\x12\x1e\n" +
	"\x1aFILTER_FIELD_TYPE_DATETIME\x10\x05\x12\x1a\n" +
	"\x16FILTER_FIELD_TYPE_ENUM\x10\x06\x12\x19\n" +
	"\x15FILTER_FIELD_TYPE_MAP\x10\a*V\n" +
	"\vFilterLogic\x12\x1c\n" +
	"\x18FILTER_LOGIC_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FILTER_LOGIC_AND\x10\x01\x12\x13\n" +
	"\x0fFILTER_LOGIC_OR\x10\x02B@Z>github.com/omniviewdev/plugin-sdk/proto/v1/resource;resourcepbb\x06proto3"

var (
	file_proto_v1_resource_filter_proto_rawDescOnce sync.Once
	file_proto_v1_resource_filter_proto_rawDescData []byte
)

func file_proto_v1_resource_filter_proto_rawDescGZIP() []byte {
	file_proto_v1_resource_filter_proto_rawDescOnce.Do(func() {
		file_proto_v1_resource_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_resource_filter_proto_rawDesc), len(file_proto_v1_resource_filter_proto_rawDesc)))
	})
	return file_proto_v1_resource_filter_proto_rawDescData
}

var file_proto_v1_resource_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_v1_resource_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_resource_filter_proto_goTypes = []any{
	(FilterOperator)(0),      // 0: omniview.sdk.resource.v1.FilterOperator
	(FilterFieldType)(0),     // 1: omniview.sdk.resource.v1.FilterFieldType
	(FilterLogic)(0),         // 2: omniview.sdk.resource.v1.FilterLogic
	(*FilterField)(nil),      // 3: omniview.sdk.resource.v1.FilterField
	(*FilterPredicate)(nil),  // 4: omniview.sdk.resource.v1.FilterPredicate
	(*FilterExpression)(nil), // 5: omniview.sdk.resource.v1.FilterExpression
	(*OrderField)(nil),       // 6: omniview.sdk.resource.v1.OrderField
	(*PaginationParams)(nil), // 7: omniview.sdk.resource.v1.PaginationParams
	(*structpb.Value)(nil),   // 8: google.protobuf.Value
}
var file_proto_v1_resource_filter_proto_depIdxs = []int32{
	1, // 0: omniview.sdk.resource.v1.FilterField.type:type_name -> omniview.sdk.resource.v1.FilterFieldType
	0, // 1: omniview.sdk.resource.v1.FilterField.operators:type_name -> omniview.sdk.resource.v1.FilterOperator
	0, // 2: omniview.sdk.resource.v1.FilterPredicate.operator:type_name -> omniview.sdk.resource.v1.FilterOperator
	8, // 3: omniview.sdk.resource.v1.FilterPredicate.value:type_name -> google.protobuf.Value
	2, // 4: omniview.sdk.resource.v1.FilterExpression.logic:type_name -> omniview.sdk.resource.v1.FilterLogic
	4, // 5: omniview.sdk.resource.v1.FilterExpression.predicates:type_name -> omniview.sdk.resource.v1.FilterPredicate
	5, // 6: omniview.sdk.resource.v1.FilterExpression.groups:type_name -> omniview.sdk.resource.v1.FilterExpression
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_v1_resource_filter_proto_init() }
func file_proto_v1_resource_filter_proto_init() {
	if File_proto_v1_resource_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_resource_filter_proto_rawDesc), len(file_proto_v1_resource_filter_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_resource_filter_proto_goTypes,
		DependencyIndexes: file_proto_v1_resource_filter_proto_depIdxs,
		EnumInfos:         file_proto_v1_resource_filter_proto_enumTypes,
		MessageInfos:      file_proto_v1_resource_filter_proto_msgTypes,
	}.Build()
	File_proto_v1_resource_filter_proto = out.File
	file_proto_v1_resource_filter_proto_goTypes = nil
	file_proto_v1_resource_filter_proto_depIdxs = nil
}
