// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/resource/health.proto

package resourcepb

import (
	_ "github.com/omniviewdev/plugin-sdk/proto/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
	HealthStatus_HEALTH_STATUS_PENDING     HealthStatus = 4
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 5
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
		4: "HEALTH_STATUS_PENDING",
		5: "HEALTH_STATUS_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
		"HEALTH_STATUS_PENDING":     4,
		"HEALTH_STATUS_UNKNOWN":     5,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{0}
}

type EventSeverity int32

const (
	EventSeverity_EVENT_SEVERITY_UNSPECIFIED EventSeverity = 0
	EventSeverity_EVENT_SEVERITY_NORMAL      EventSeverity = 1
	EventSeverity_EVENT_SEVERITY_WARNING     EventSeverity = 2
	EventSeverity_EVENT_SEVERITY_ERROR       EventSeverity = 3
)

// Enum value maps for EventSeverity.
var (
	EventSeverity_name = map[int32]string{
		0: "EVENT_SEVERITY_UNSPECIFIED",
		1: "EVENT_SEVERITY_NORMAL",
		2: "EVENT_SEVERITY_WARNING",
		3: "EVENT_SEVERITY_ERROR",
	}
	EventSeverity_value = map[string]int32{
		"EVENT_SEVERITY_UNSPECIFIED": 0,
		"EVENT_SEVERITY_NORMAL":      1,
		"EVENT_SEVERITY_WARNING":     2,
		"EVENT_SEVERITY_ERROR":       3,
	}
)

func (x EventSeverity) Enum() *EventSeverity {
	p := new(EventSeverity)
	*p = x
	return p
}

func (x EventSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_health_proto_enumTypes[1].Descriptor()
}

func (EventSeverity) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_health_proto_enumTypes[1]
}

func (x EventSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSeverity.Descriptor instead.
func (EventSeverity) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{1}
}

// ResourceHealth is the normalized health assessment for a resource.
type ResourceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=omniview.sdk.resource.v1.HealthStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3,oneof" json:"since,omitempty"`
	Conditions    []*HealthCondition     `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceHealth) Reset() {
	*x = ResourceHealth{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHealth) ProtoMessage() {}

func (x *ResourceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHealth.ProtoReflect.Descriptor instead.
func (*ResourceHealth) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceHealth) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *ResourceHealth) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResourceHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceHealth) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ResourceHealth) GetConditions() []*HealthCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// HealthCondition is a single health condition (Ready, Scheduled, etc.).
type HealthCondition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastProbeTime      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_probe_time,json=lastProbeTime,proto3,oneof" json:"last_probe_time,omitempty"`
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_transition_time,json=lastTransitionTime,proto3,oneof" json:"last_transition_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCondition) Reset() {
	*x = HealthCondition{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCondition) ProtoMessage() {}

func (x *HealthCondition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCondition.ProtoReflect.Descriptor instead.
func (*HealthCondition) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HealthCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCondition) GetLastProbeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastProbeTime
	}
	return nil
}

func (x *HealthCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

// ResourceEvent is a diagnostic event.
type ResourceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventSeverity          `protobuf:"varint,1,opt,name=type,proto3,enum=omniview.sdk.resource.v1.EventSeverity" json:"type,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEvent) Reset() {
	*x = ResourceEvent{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEvent) ProtoMessage() {}

func (x *ResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEvent.ProtoReflect.Descriptor instead.
func (*ResourceEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceEvent) GetType() EventSeverity {
	if x != nil {
		return x.Type
	}
	return EventSeverity_EVENT_SEVERITY_UNSPECIFIED
}

func (x *ResourceEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResourceEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ResourceEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResourceEvent) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *ResourceEvent) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

// AnnotatedNode is a resource with health and event context.
type AnnotatedNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ResourceRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Health        *ResourceHealth        `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	Events        []*ResourceEvent       `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotatedNode) Reset() {
	*x = AnnotatedNode{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotatedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotatedNode) ProtoMessage() {}

func (x *AnnotatedNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotatedNode.ProtoReflect.Descriptor instead.
func (*AnnotatedNode) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{3}
}

func (x *AnnotatedNode) GetRef() *ResourceRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *AnnotatedNode) GetHealth() *ResourceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *AnnotatedNode) GetEvents() []*ResourceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// AnnotatedEdge is a relationship edge with health on the target.
type AnnotatedEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *RelationshipEdge      `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	Target        *AnnotatedNode         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotatedEdge) Reset() {
	*x = AnnotatedEdge{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotatedEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotatedEdge) ProtoMessage() {}

func (x *AnnotatedEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotatedEdge.ProtoReflect.Descriptor instead.
func (*AnnotatedEdge) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{4}
}

func (x *AnnotatedEdge) GetEdge() *RelationshipEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *AnnotatedEdge) GetTarget() *AnnotatedNode {
	if x != nil {
		return x.Target
	}
	return nil
}

// DiagnosticContext is the complete debugging context for a single resource.
type DiagnosticContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      []byte                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Health        *ResourceHealth        `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	Events        []*ResourceEvent       `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Related       []*AnnotatedEdge       `protobuf:"bytes,4,rep,name=related,proto3" json:"related,omitempty"`
	OwnerChain    []*AnnotatedNode       `protobuf:"bytes,5,rep,name=owner_chain,json=ownerChain,proto3" json:"owner_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticContext) Reset() {
	*x = DiagnosticContext{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticContext) ProtoMessage() {}

func (x *DiagnosticContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticContext.ProtoReflect.Descriptor instead.
func (*DiagnosticContext) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{5}
}

func (x *DiagnosticContext) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DiagnosticContext) GetHealth() *ResourceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *DiagnosticContext) GetEvents() []*ResourceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DiagnosticContext) GetRelated() []*AnnotatedEdge {
	if x != nil {
		return x.Related
	}
	return nil
}

func (x *DiagnosticContext) GetOwnerChain() []*AnnotatedNode {
	if x != nil {
		return x.OwnerChain
	}
	return nil
}

// DiagnosticTree is a health-annotated dependency tree for UI rendering.
type DiagnosticTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *AnnotatedNode         `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Children      []*DiagnosticBranch    `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticTree) Reset() {
	*x = DiagnosticTree{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticTree) ProtoMessage() {}

func (x *DiagnosticTree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticTree.ProtoReflect.Descriptor instead.
func (*DiagnosticTree) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{6}
}

func (x *DiagnosticTree) GetRoot() *AnnotatedNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *DiagnosticTree) GetChildren() []*DiagnosticBranch {
	if x != nil {
		return x.Children
	}
	return nil
}

// DiagnosticBranch is a node in the diagnostic tree (self-referencing).
type DiagnosticBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *RelationshipEdge      `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	Node          *AnnotatedNode         `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Children      []*DiagnosticBranch    `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticBranch) Reset() {
	*x = DiagnosticBranch{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticBranch) ProtoMessage() {}

func (x *DiagnosticBranch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticBranch.ProtoReflect.Descriptor instead.
func (*DiagnosticBranch) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{7}
}

func (x *DiagnosticBranch) GetEdge() *RelationshipEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *DiagnosticBranch) GetNode() *AnnotatedNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *DiagnosticBranch) GetChildren() []*DiagnosticBranch {
	if x != nil {
		return x.Children
	}
	return nil
}

// ImpactReport describes what would be affected by a resource failure/removal.
type ImpactReport struct {
	state                protoimpl.MessageState        `protogen:"open.v1"`
	Target               *ResourceRef                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	DirectDependents     map[string]*AnnotatedNodeList `protobuf:"bytes,2,rep,name=direct_dependents,json=directDependents,proto3" json:"direct_dependents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TransitiveDependents map[string]*AnnotatedNodeList `protobuf:"bytes,3,rep,name=transitive_dependents,json=transitiveDependents,proto3" json:"transitive_dependents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Summary              string                        `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	AffectedCounts       map[string]int32              `protobuf:"bytes,5,rep,name=affected_counts,json=affectedCounts,proto3" json:"affected_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImpactReport) Reset() {
	*x = ImpactReport{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactReport) ProtoMessage() {}

func (x *ImpactReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactReport.ProtoReflect.Descriptor instead.
func (*ImpactReport) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{8}
}

func (x *ImpactReport) GetTarget() *ResourceRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ImpactReport) GetDirectDependents() map[string]*AnnotatedNodeList {
	if x != nil {
		return x.DirectDependents
	}
	return nil
}

func (x *ImpactReport) GetTransitiveDependents() map[string]*AnnotatedNodeList {
	if x != nil {
		return x.TransitiveDependents
	}
	return nil
}

func (x *ImpactReport) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ImpactReport) GetAffectedCounts() map[string]int32 {
	if x != nil {
		return x.AffectedCounts
	}
	return nil
}

// AnnotatedNodeList wraps repeated AnnotatedNode for use as proto map value.
type AnnotatedNodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*AnnotatedNode       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotatedNodeList) Reset() {
	*x = AnnotatedNodeList{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotatedNodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotatedNodeList) ProtoMessage() {}

func (x *AnnotatedNodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotatedNodeList.ProtoReflect.Descriptor instead.
func (*AnnotatedNodeList) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{9}
}

func (x *AnnotatedNodeList) GetNodes() []*AnnotatedNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// CommonCauseResult identifies shared dependencies between multiple resources.
type CommonCauseResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Resources          []*ResourceRef         `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	SharedDependencies []*AnnotatedNode       `protobuf:"bytes,2,rep,name=shared_dependencies,json=sharedDependencies,proto3" json:"shared_dependencies,omitempty"`
	SharedByCount      []*SharedDependency    `protobuf:"bytes,3,rep,name=shared_by_count,json=sharedByCount,proto3" json:"shared_by_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommonCauseResult) Reset() {
	*x = CommonCauseResult{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonCauseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonCauseResult) ProtoMessage() {}

func (x *CommonCauseResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonCauseResult.ProtoReflect.Descriptor instead.
func (*CommonCauseResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{10}
}

func (x *CommonCauseResult) GetResources() []*ResourceRef {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CommonCauseResult) GetSharedDependencies() []*AnnotatedNode {
	if x != nil {
		return x.SharedDependencies
	}
	return nil
}

func (x *CommonCauseResult) GetSharedByCount() []*SharedDependency {
	if x != nil {
		return x.SharedByCount
	}
	return nil
}

// SharedDependency groups a dependency by how many input resources share it.
type SharedDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *AnnotatedNode         `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	SharedBy      int32                  `protobuf:"varint,2,opt,name=shared_by,json=sharedBy,proto3" json:"shared_by,omitempty"`
	TotalInput    int32                  `protobuf:"varint,3,opt,name=total_input,json=totalInput,proto3" json:"total_input,omitempty"`
	DependedBy    []*ResourceRef         `protobuf:"bytes,4,rep,name=depended_by,json=dependedBy,proto3" json:"depended_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedDependency) Reset() {
	*x = SharedDependency{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedDependency) ProtoMessage() {}

func (x *SharedDependency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedDependency.ProtoReflect.Descriptor instead.
func (*SharedDependency) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{11}
}

func (x *SharedDependency) GetResource() *AnnotatedNode {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *SharedDependency) GetSharedBy() int32 {
	if x != nil {
		return x.SharedBy
	}
	return 0
}

func (x *SharedDependency) GetTotalInput() int32 {
	if x != nil {
		return x.TotalInput
	}
	return 0
}

func (x *SharedDependency) GetDependedBy() []*ResourceRef {
	if x != nil {
		return x.DependedBy
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,2,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{12}
}

func (x *HealthRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *HealthRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *HealthRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ResourceHealth        `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetHealth() *ResourceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type ResourceEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,2,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEventsRequest) Reset() {
	*x = ResourceEventsRequest{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEventsRequest) ProtoMessage() {}

func (x *ResourceEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEventsRequest.ProtoReflect.Descriptor instead.
func (*ResourceEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceEventsRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ResourceEventsRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *ResourceEventsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceEventsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ResourceEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ResourceEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEventsResponse) Reset() {
	*x = ResourceEventsResponse{}
	mi := &file_proto_v1_resource_health_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEventsResponse) ProtoMessage() {}

func (x *ResourceEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_health_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEventsResponse.ProtoReflect.Descriptor instead.
func (*ResourceEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_health_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceEventsResponse) GetEvents() []*ResourceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_v1_resource_health_proto protoreflect.FileDescriptor

const file_proto_v1_resource_health_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/v1/resource/health.proto\x12\x18omniview.sdk.resource.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cproto/v1/common/common.proto\x1a$proto/v1/resource/relationship.proto\"\x8e\x02\n" +
	"\x0eResourceHealth\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.omniview.sdk.resource.v1.HealthStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x125\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05since\x88\x01\x01\x12I\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2).omniview.sdk.resource.v1.HealthConditionR\n" +
	"conditionsB\b\n" +
	"\x06_since\"\xb8\x02\n" +
	"\x0fHealthCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12G\n" +
	"\x0flast_probe_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rlastProbeTime\x88\x01\x01\x12Q\n" +
	"\x14last_transition_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x12lastTransitionTime\x88\x01\x01B\x12\n" +
	"\x10_last_probe_timeB\x17\n" +
	"\x15_last_transition_time\"\xa0\x02\n" +
	"\rResourceEvent\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.omniview.sdk.resource.v1.EventSeverityR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x129\n" +
	"\n" +
	"first_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xcb\x01\n" +
	"\rAnnotatedNode\x127\n" +
	"\x03ref\x18\x01 \x01(\v2%.omniview.sdk.resource.v1.ResourceRefR\x03ref\x12@\n" +
	"\x06health\x18\x02 \x01(\v2(.omniview.sdk.resource.v1.ResourceHealthR\x06health\x12?\n" +
	"\x06events\x18\x03 \x03(\v2'.omniview.sdk.resource.v1.ResourceEventR\x06events\"\x90\x01\n" +
	"\rAnnotatedEdge\x12>\n" +
	"\x04edge\x18\x01 \x01(\v2*.omniview.sdk.resource.v1.RelationshipEdgeR\x04edge\x12?\n" +
	"\x06target\x18\x02 \x01(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\x06target\"\xbf\x02\n" +
	"\x11DiagnosticContext\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\fR\bresource\x12@\n" +
	"\x06health\x18\x02 \x01(\v2(.omniview.sdk.resource.v1.ResourceHealthR\x06health\x12?\n" +
	"\x06events\x18\x03 \x03(\v2'.omniview.sdk.resource.v1.ResourceEventR\x06events\x12A\n" +
	"\arelated\x18\x04 \x03(\v2'.omniview.sdk.resource.v1.AnnotatedEdgeR\arelated\x12H\n" +
	"\vowner_chain\x18\x05 \x03(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\n" +
	"ownerChain\"\x95\x01\n" +
	"\x0eDiagnosticTree\x12;\n" +
	"\x04root\x18\x01 \x01(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\x04root\x12F\n" +
	"\bchildren\x18\x02 \x03(\v2*.omniview.sdk.resource.v1.DiagnosticBranchR\bchildren\"\xd7\x01\n" +
	"\x10DiagnosticBranch\x12>\n" +
	"\x04edge\x18\x01 \x01(\v2*.omniview.sdk.resource.v1.RelationshipEdgeR\x04edge\x12;\n" +
	"\x04node\x18\x02 \x01(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\x04node\x12F\n" +
	"\bchildren\x18\x03 \x03(\v2*.omniview.sdk.resource.v1.DiagnosticBranchR\bchildren\"\xd9\x05\n" +
	"\fImpactReport\x12=\n" +
	"\x06target\x18\x01 \x01(\v2%.omniview.sdk.resource.v1.ResourceRefR\x06target\x12i\n" +
	"\x11direct_dependents\x18\x02 \x03(\v2<.omniview.sdk.resource.v1.ImpactReport.DirectDependentsEntryR\x10directDependents\x12u\n" +
	"\x15transitive_dependents\x18\x03 \x03(\v2@.omniview.sdk.resource.v1.ImpactReport.TransitiveDependentsEntryR\x14transitiveDependents\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12c\n" +
	"\x0faffected_counts\x18\x05 \x03(\v2:.omniview.sdk.resource.v1.ImpactReport.AffectedCountsEntryR\x0eaffectedCounts\x1ap\n" +
	"\x15DirectDependentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.omniview.sdk.resource.v1.AnnotatedNodeListR\x05value:\x028\x01\x1at\n" +
	"\x19TransitiveDependentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.omniview.sdk.resource.v1.AnnotatedNodeListR\x05value:\x028\x01\x1aA\n" +
	"\x13AffectedCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"R\n" +
	"\x11AnnotatedNodeList\x12=\n" +
	"\x05nodes\x18\x01 \x03(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\x05nodes\"\x86\x02\n" +
	"\x11CommonCauseResult\x12C\n" +
	"\tresources\x18\x01 \x03(\v2%.omniview.sdk.resource.v1.ResourceRefR\tresources\x12X\n" +
	"\x13shared_dependencies\x18\x02 \x03(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\x12sharedDependencies\x12R\n" +
	"\x0fshared_by_count\x18\x03 \x03(\v2*.omniview.sdk.resource.v1.SharedDependencyR\rsharedByCount\"\xdd\x01\n" +
	"\x10SharedDependency\x12C\n" +
	"\bresource\x18\x01 \x01(\v2'.omniview.sdk.resource.v1.AnnotatedNodeR\bresource\x12\x1b\n" +
	"\tshared_by\x18\x02 \x01(\x05R\bsharedBy\x12\x1f\n" +
	"\vtotal_input\x18\x03 \x01(\x05R\n" +
	"totalInput\x12F\n" +
	"\vdepended_by\x18\x04 \x03(\v2%.omniview.sdk.resource.v1.ResourceRefR\n" +
	"dependedBy\"k\n" +
	"\rHealthRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x02 \x01(\tR\vresourceKey\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"R\n" +
	"\x0eHealthResponse\x12@\n" +
	"\x06health\x18\x01 \x01(\v2(.omniview.sdk.resource.v1.ResourceHealthR\x06health\"\xa3\x01\n" +
	"\x15ResourceEventsRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x02 \x01(\tR\vresourceKey\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"Y\n" +
	"\x16ResourceEventsResponse\x12?\n" +
	"\x06events\x18\x01 \x03(\v2'.omniview.sdk.resource.v1.ResourceEventR\x06events*\xb7\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03\x12\x19\n" +
	"\x15HEALTH_STATUS_PENDING\x10\x04\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x05*\x80\x01\n" +
	"\rEventSeverity\x12\x1e\n" +
	"\x1aEVENT_SEVERITY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_SEVERITY_NORMAL\x10\x01\x12\x1a\n" +
	"\x16EVENT_SEVERITY_WARNING\x10\x02\x12\x18\n" +
	"\x14EVENT_SEVERITY_ERROR\x10\x03B@Z>github.com/omniviewdev/plugin-sdk/proto/v1/resource;resourcepbb\x06proto3"

var (
	file_proto_v1_resource_health_proto_rawDescOnce sync.Once
	file_proto_v1_resource_health_proto_rawDescData []byte
)

func file_proto_v1_resource_health_proto_rawDescGZIP() []byte {
	file_proto_v1_resource_health_proto_rawDescOnce.Do(func() {
		file_proto_v1_resource_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_resource_health_proto_rawDesc), len(file_proto_v1_resource_health_proto_rawDesc)))
	})
	return file_proto_v1_resource_health_proto_rawDescData
}

var file_proto_v1_resource_health_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v1_resource_health_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_v1_resource_health_proto_goTypes = []any{
	(HealthStatus)(0),              // 0: omniview.sdk.resource.v1.HealthStatus
	(EventSeverity)(0),             // 1: omniview.sdk.resource.v1.EventSeverity
	(*ResourceHealth)(nil),         // 2: omniview.sdk.resource.v1.ResourceHealth
	(*HealthCondition)(nil),        // 3: omniview.sdk.resource.v1.HealthCondition
	(*ResourceEvent)(nil),          // 4: omniview.sdk.resource.v1.ResourceEvent
	(*AnnotatedNode)(nil),          // 5: omniview.sdk.resource.v1.AnnotatedNode
	(*AnnotatedEdge)(nil),          // 6: omniview.sdk.resource.v1.AnnotatedEdge
	(*DiagnosticContext)(nil),      // 7: omniview.sdk.resource.v1.DiagnosticContext
	(*DiagnosticTree)(nil),         // 8: omniview.sdk.resource.v1.DiagnosticTree
	(*DiagnosticBranch)(nil),       // 9: omniview.sdk.resource.v1.DiagnosticBranch
	(*ImpactReport)(nil),           // 10: omniview.sdk.resource.v1.ImpactReport
	(*AnnotatedNodeList)(nil),      // 11: omniview.sdk.resource.v1.AnnotatedNodeList
	(*CommonCauseResult)(nil),      // 12: omniview.sdk.resource.v1.CommonCauseResult
	(*SharedDependency)(nil),       // 13: omniview.sdk.resource.v1.SharedDependency
	(*HealthRequest)(nil),          // 14: omniview.sdk.resource.v1.HealthRequest
	(*HealthResponse)(nil),         // 15: omniview.sdk.resource.v1.HealthResponse
	(*ResourceEventsRequest)(nil),  // 16: omniview.sdk.resource.v1.ResourceEventsRequest
	(*ResourceEventsResponse)(nil), // 17: omniview.sdk.resource.v1.ResourceEventsResponse
	nil,                            // 18: omniview.sdk.resource.v1.ImpactReport.DirectDependentsEntry
	nil,                            // 19: omniview.sdk.resource.v1.ImpactReport.TransitiveDependentsEntry
	nil,                            // 20: omniview.sdk.resource.v1.ImpactReport.AffectedCountsEntry
	(*timestamppb.Timestamp)(nil),  // 21: google.protobuf.Timestamp
	(*ResourceRef)(nil),            // 22: omniview.sdk.resource.v1.ResourceRef
	(*RelationshipEdge)(nil),       // 23: omniview.sdk.resource.v1.RelationshipEdge
}
var file_proto_v1_resource_health_proto_depIdxs = []int32{
	0,  // 0: omniview.sdk.resource.v1.ResourceHealth.status:type_name -> omniview.sdk.resource.v1.HealthStatus
	21, // 1: omniview.sdk.resource.v1.ResourceHealth.since:type_name -> google.protobuf.Timestamp
	3,  // 2: omniview.sdk.resource.v1.ResourceHealth.conditions:type_name -> omniview.sdk.resource.v1.HealthCondition
	21, // 3: omniview.sdk.resource.v1.HealthCondition.last_probe_time:type_name -> google.protobuf.Timestamp
	21, // 4: omniview.sdk.resource.v1.HealthCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	1,  // 5: omniview.sdk.resource.v1.ResourceEvent.type:type_name -> omniview.sdk.resource.v1.EventSeverity
	21, // 6: omniview.sdk.resource.v1.ResourceEvent.first_seen:type_name -> google.protobuf.Timestamp
	21, // 7: omniview.sdk.resource.v1.ResourceEvent.last_seen:type_name -> google.protobuf.Timestamp
	22, // 8: omniview.sdk.resource.v1.AnnotatedNode.ref:type_name -> omniview.sdk.resource.v1.ResourceRef
	2,  // 9: omniview.sdk.resource.v1.AnnotatedNode.health:type_name -> omniview.sdk.resource.v1.ResourceHealth
	4,  // 10: omniview.sdk.resource.v1.AnnotatedNode.events:type_name -> omniview.sdk.resource.v1.ResourceEvent
	23, // 11: omniview.sdk.resource.v1.AnnotatedEdge.edge:type_name -> omniview.sdk.resource.v1.RelationshipEdge
	5,  // 12: omniview.sdk.resource.v1.AnnotatedEdge.target:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	2,  // 13: omniview.sdk.resource.v1.DiagnosticContext.health:type_name -> omniview.sdk.resource.v1.ResourceHealth
	4,  // 14: omniview.sdk.resource.v1.DiagnosticContext.events:type_name -> omniview.sdk.resource.v1.ResourceEvent
	6,  // 15: omniview.sdk.resource.v1.DiagnosticContext.related:type_name -> omniview.sdk.resource.v1.AnnotatedEdge
	5,  // 16: omniview.sdk.resource.v1.DiagnosticContext.owner_chain:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	5,  // 17: omniview.sdk.resource.v1.DiagnosticTree.root:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	9,  // 18: omniview.sdk.resource.v1.DiagnosticTree.children:type_name -> omniview.sdk.resource.v1.DiagnosticBranch
	23, // 19: omniview.sdk.resource.v1.DiagnosticBranch.edge:type_name -> omniview.sdk.resource.v1.RelationshipEdge
	5,  // 20: omniview.sdk.resource.v1.DiagnosticBranch.node:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	9,  // 21: omniview.sdk.resource.v1.DiagnosticBranch.children:type_name -> omniview.sdk.resource.v1.DiagnosticBranch
	22, // 22: omniview.sdk.resource.v1.ImpactReport.target:type_name -> omniview.sdk.resource.v1.ResourceRef
	18, // 23: omniview.sdk.resource.v1.ImpactReport.direct_dependents:type_name -> omniview.sdk.resource.v1.ImpactReport.DirectDependentsEntry
	19, // 24: omniview.sdk.resource.v1.ImpactReport.transitive_dependents:type_name -> omniview.sdk.resource.v1.ImpactReport.TransitiveDependentsEntry
	20, // 25: omniview.sdk.resource.v1.ImpactReport.affected_counts:type_name -> omniview.sdk.resource.v1.ImpactReport.AffectedCountsEntry
	5,  // 26: omniview.sdk.resource.v1.AnnotatedNodeList.nodes:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	22, // 27: omniview.sdk.resource.v1.CommonCauseResult.resources:type_name -> omniview.sdk.resource.v1.ResourceRef
	5,  // 28: omniview.sdk.resource.v1.CommonCauseResult.shared_dependencies:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	13, // 29: omniview.sdk.resource.v1.CommonCauseResult.shared_by_count:type_name -> omniview.sdk.resource.v1.SharedDependency
	5,  // 30: omniview.sdk.resource.v1.SharedDependency.resource:type_name -> omniview.sdk.resource.v1.AnnotatedNode
	22, // 31: omniview.sdk.resource.v1.SharedDependency.depended_by:type_name -> omniview.sdk.resource.v1.ResourceRef
	2,  // 32: omniview.sdk.resource.v1.HealthResponse.health:type_name -> omniview.sdk.resource.v1.ResourceHealth
	4,  // 33: omniview.sdk.resource.v1.ResourceEventsResponse.events:type_name -> omniview.sdk.resource.v1.ResourceEvent
	11, // 34: omniview.sdk.resource.v1.ImpactReport.DirectDependentsEntry.value:type_name -> omniview.sdk.resource.v1.AnnotatedNodeList
	11, // 35: omniview.sdk.resource.v1.ImpactReport.TransitiveDependentsEntry.value:type_name -> omniview.sdk.resource.v1.AnnotatedNodeList
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_v1_resource_health_proto_init() }
func file_proto_v1_resource_health_proto_init() {
	if File_proto_v1_resource_health_proto != nil {
		return
	}
	file_proto_v1_resource_relationship_proto_init()
	file_proto_v1_resource_health_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_v1_resource_health_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_resource_health_proto_rawDesc), len(file_proto_v1_resource_health_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_resource_health_proto_goTypes,
		DependencyIndexes: file_proto_v1_resource_health_proto_depIdxs,
		EnumInfos:         file_proto_v1_resource_health_proto_enumTypes,
		MessageInfos:      file_proto_v1_resource_health_proto_msgTypes,
	}.Build()
	File_proto_v1_resource_health_proto = out.File
	file_proto_v1_resource_health_proto_goTypes = nil
	file_proto_v1_resource_health_proto_depIdxs = nil
}
