// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/resource/relationship.proto

package resourcepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationshipType int32

const (
	RelationshipType_RELATIONSHIP_TYPE_UNSPECIFIED RelationshipType = 0
	RelationshipType_RELATIONSHIP_TYPE_OWNS        RelationshipType = 1
	RelationshipType_RELATIONSHIP_TYPE_RUNS_ON     RelationshipType = 2
	RelationshipType_RELATIONSHIP_TYPE_USES        RelationshipType = 3
	RelationshipType_RELATIONSHIP_TYPE_EXPOSES     RelationshipType = 4
	RelationshipType_RELATIONSHIP_TYPE_MANAGES     RelationshipType = 5
	RelationshipType_RELATIONSHIP_TYPE_MEMBER_OF   RelationshipType = 6
)

// Enum value maps for RelationshipType.
var (
	RelationshipType_name = map[int32]string{
		0: "RELATIONSHIP_TYPE_UNSPECIFIED",
		1: "RELATIONSHIP_TYPE_OWNS",
		2: "RELATIONSHIP_TYPE_RUNS_ON",
		3: "RELATIONSHIP_TYPE_USES",
		4: "RELATIONSHIP_TYPE_EXPOSES",
		5: "RELATIONSHIP_TYPE_MANAGES",
		6: "RELATIONSHIP_TYPE_MEMBER_OF",
	}
	RelationshipType_value = map[string]int32{
		"RELATIONSHIP_TYPE_UNSPECIFIED": 0,
		"RELATIONSHIP_TYPE_OWNS":        1,
		"RELATIONSHIP_TYPE_RUNS_ON":     2,
		"RELATIONSHIP_TYPE_USES":        3,
		"RELATIONSHIP_TYPE_EXPOSES":     4,
		"RELATIONSHIP_TYPE_MANAGES":     5,
		"RELATIONSHIP_TYPE_MEMBER_OF":   6,
	}
)

func (x RelationshipType) Enum() *RelationshipType {
	p := new(RelationshipType)
	*p = x
	return p
}

func (x RelationshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_relationship_proto_enumTypes[0].Descriptor()
}

func (RelationshipType) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_relationship_proto_enumTypes[0]
}

func (x RelationshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationshipType.Descriptor instead.
func (RelationshipType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{0}
}

// RelationshipDescriptor declares a relationship from one resource type to another.
type RelationshipDescriptor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              RelationshipType       `protobuf:"varint,1,opt,name=type,proto3,enum=omniview.sdk.resource.v1.RelationshipType" json:"type,omitempty"`
	TargetResourceKey string                 `protobuf:"bytes,2,opt,name=target_resource_key,json=targetResourceKey,proto3" json:"target_resource_key,omitempty"`
	Label             string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	InverseLabel      string                 `protobuf:"bytes,4,opt,name=inverse_label,json=inverseLabel,proto3" json:"inverse_label,omitempty"`
	Cardinality       string                 `protobuf:"bytes,5,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	Extractor         *RelationshipExtractor `protobuf:"bytes,6,opt,name=extractor,proto3" json:"extractor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelationshipDescriptor) Reset() {
	*x = RelationshipDescriptor{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipDescriptor) ProtoMessage() {}

func (x *RelationshipDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipDescriptor.ProtoReflect.Descriptor instead.
func (*RelationshipDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *RelationshipDescriptor) GetType() RelationshipType {
	if x != nil {
		return x.Type
	}
	return RelationshipType_RELATIONSHIP_TYPE_UNSPECIFIED
}

func (x *RelationshipDescriptor) GetTargetResourceKey() string {
	if x != nil {
		return x.TargetResourceKey
	}
	return ""
}

func (x *RelationshipDescriptor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RelationshipDescriptor) GetInverseLabel() string {
	if x != nil {
		return x.InverseLabel
	}
	return ""
}

func (x *RelationshipDescriptor) GetCardinality() string {
	if x != nil {
		return x.Cardinality
	}
	return ""
}

func (x *RelationshipDescriptor) GetExtractor() *RelationshipExtractor {
	if x != nil {
		return x.Extractor
	}
	return nil
}

// RelationshipExtractor defines how to find related resource IDs from source data.
type RelationshipExtractor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	FieldPath     string                 `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	OwnerRefKind  string                 `protobuf:"bytes,3,opt,name=owner_ref_kind,json=ownerRefKind,proto3" json:"owner_ref_kind,omitempty"`
	LabelSelector map[string]string      `protobuf:"bytes,4,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipExtractor) Reset() {
	*x = RelationshipExtractor{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipExtractor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipExtractor) ProtoMessage() {}

func (x *RelationshipExtractor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipExtractor.ProtoReflect.Descriptor instead.
func (*RelationshipExtractor) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{1}
}

func (x *RelationshipExtractor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RelationshipExtractor) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *RelationshipExtractor) GetOwnerRefKind() string {
	if x != nil {
		return x.OwnerRefKind
	}
	return ""
}

func (x *RelationshipExtractor) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

// ResourceRef is a reference to a specific resource instance.
type ResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,3,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRef) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ResourceRef) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ResourceRef) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *ResourceRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRef) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// ResolvedRelationship contains actual relationship instances for a resource.
type ResolvedRelationship struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Descriptor_   *RelationshipDescriptor `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Targets       []*ResourceRef          `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedRelationship) Reset() {
	*x = ResolvedRelationship{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedRelationship) ProtoMessage() {}

func (x *ResolvedRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedRelationship.ProtoReflect.Descriptor instead.
func (*ResolvedRelationship) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{3}
}

func (x *ResolvedRelationship) GetDescriptor_() *RelationshipDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *ResolvedRelationship) GetTargets() []*ResourceRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

// RelationshipEdge is a single edge in the relationship graph.
type RelationshipEdge struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Source        *ResourceRef            `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        *ResourceRef            `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Descriptor_   *RelationshipDescriptor `protobuf:"bytes,3,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipEdge) Reset() {
	*x = RelationshipEdge{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipEdge) ProtoMessage() {}

func (x *RelationshipEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipEdge.ProtoReflect.Descriptor instead.
func (*RelationshipEdge) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{4}
}

func (x *RelationshipEdge) GetSource() *ResourceRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RelationshipEdge) GetTarget() *ResourceRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RelationshipEdge) GetDescriptor_() *RelationshipDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

// DependencyTree is an ownership/dependency hierarchy rooted at a resource.
type DependencyTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *ResourceRef           `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Children      []*DependencyNode      `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyTree) Reset() {
	*x = DependencyTree{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyTree) ProtoMessage() {}

func (x *DependencyTree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyTree.ProtoReflect.Descriptor instead.
func (*DependencyTree) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{5}
}

func (x *DependencyTree) GetRoot() *ResourceRef {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *DependencyTree) GetChildren() []*DependencyNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// DependencyNode is a node in the dependency tree (self-referencing).
type DependencyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *RelationshipEdge      `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	Children      []*DependencyNode      `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyNode) Reset() {
	*x = DependencyNode{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyNode) ProtoMessage() {}

func (x *DependencyNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyNode.ProtoReflect.Descriptor instead.
func (*DependencyNode) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{6}
}

func (x *DependencyNode) GetEdge() *RelationshipEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *DependencyNode) GetChildren() []*DependencyNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type RelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceKey   string                 `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipsRequest) Reset() {
	*x = RelationshipsRequest{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipsRequest) ProtoMessage() {}

func (x *RelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipsRequest.ProtoReflect.Descriptor instead.
func (*RelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{7}
}

func (x *RelationshipsRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

type RelationshipsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Relationships []*RelationshipDescriptor `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipsResponse) Reset() {
	*x = RelationshipsResponse{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipsResponse) ProtoMessage() {}

func (x *RelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipsResponse.ProtoReflect.Descriptor instead.
func (*RelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{8}
}

func (x *RelationshipsResponse) GetRelationships() []*RelationshipDescriptor {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type ResolveRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,2,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRelationshipsRequest) Reset() {
	*x = ResolveRelationshipsRequest{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRelationshipsRequest) ProtoMessage() {}

func (x *ResolveRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*ResolveRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveRelationshipsRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ResolveRelationshipsRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *ResolveRelationshipsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveRelationshipsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ResolveRelationshipsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Relationships []*ResolvedRelationship `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRelationshipsResponse) Reset() {
	*x = ResolveRelationshipsResponse{}
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRelationshipsResponse) ProtoMessage() {}

func (x *ResolveRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_relationship_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*ResolveRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_relationship_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveRelationshipsResponse) GetRelationships() []*ResolvedRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

var File_proto_v1_resource_relationship_proto protoreflect.FileDescriptor

const file_proto_v1_resource_relationship_proto_rawDesc = "" +
	"\n" +
	"$proto/v1/resource/relationship.proto\x12\x18omniview.sdk.resource.v1\"\xb4\x02\n" +
	"\x16RelationshipDescriptor\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.omniview.sdk.resource.v1.RelationshipTypeR\x04type\x12.\n" +
	"\x13target_resource_key\x18\x02 \x01(\tR\x11targetResourceKey\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12#\n" +
	"\rinverse_label\x18\x04 \x01(\tR\finverseLabel\x12 \n" +
	"\vcardinality\x18\x05 \x01(\tR\vcardinality\x12M\n" +
	"\textractor\x18\x06 \x01(\v2/.omniview.sdk.resource.v1.RelationshipExtractorR\textractor\"\xa1\x02\n" +
	"\x15RelationshipExtractor\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12$\n" +
	"\x0eowner_ref_kind\x18\x03 \x01(\tR\fownerRefKind\x12i\n" +
	"\x0elabel_selector\x18\x04 \x03(\v2B.omniview.sdk.resource.v1.RelationshipExtractor.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\vResourceRef\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x03 \x01(\tR\vresourceKey\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\"\xa9\x01\n" +
	"\x14ResolvedRelationship\x12P\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v20.omniview.sdk.resource.v1.RelationshipDescriptorR\n" +
	"descriptor\x12?\n" +
	"\atargets\x18\x02 \x03(\v2%.omniview.sdk.resource.v1.ResourceRefR\atargets\"\xe2\x01\n" +
	"\x10RelationshipEdge\x12=\n" +
	"\x06source\x18\x01 \x01(\v2%.omniview.sdk.resource.v1.ResourceRefR\x06source\x12=\n" +
	"\x06target\x18\x02 \x01(\v2%.omniview.sdk.resource.v1.ResourceRefR\x06target\x12P\n" +
	"\n" +
	"descriptor\x18\x03 \x01(\v20.omniview.sdk.resource.v1.RelationshipDescriptorR\n" +
	"descriptor\"\x91\x01\n" +
	"\x0eDependencyTree\x129\n" +
	"\x04root\x18\x01 \x01(\v2%.omniview.sdk.resource.v1.ResourceRefR\x04root\x12D\n" +
	"\bchildren\x18\x02 \x03(\v2(.omniview.sdk.resource.v1.DependencyNodeR\bchildren\"\x96\x01\n" +
	"\x0eDependencyNode\x12>\n" +
	"\x04edge\x18\x01 \x01(\v2*.omniview.sdk.resource.v1.RelationshipEdgeR\x04edge\x12D\n" +
	"\bchildren\x18\x02 \x03(\v2(.omniview.sdk.resource.v1.DependencyNodeR\bchildren\"9\n" +
	"\x14RelationshipsRequest\x12!\n" +
	"\fresource_key\x18\x01 \x01(\tR\vresourceKey\"o\n" +
	"\x15RelationshipsResponse\x12V\n" +
	"\rrelationships\x18\x01 \x03(\v20.omniview.sdk.resource.v1.RelationshipDescriptorR\rrelationships\"\x93\x01\n" +
	"\x1bResolveRelationshipsRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x02 \x01(\tR\vresourceKey\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"t\n" +
	"\x1cResolveRelationshipsResponse\x12T\n" +
	"\rrelationships\x18\x01 \x03(\v2..omniview.sdk.resource.v1.ResolvedRelationshipR\rrelationships*\xeb\x01\n" +
	"\x10RelationshipType\x12!\n" +
	"\x1dRELATIONSHIP_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RELATIONSHIP_TYPE_OWNS\x10\x01\x12\x1d\n" +
	"\x19RELATIONSHIP_TYPE_RUNS_ON\x10\x02\x12\x1a\n" +
	"\x16RELATIONSHIP_TYPE_USES\x10\x03\x12\x1d\n" +
	"\x19RELATIONSHIP_TYPE_EXPOSES\x10\x04\x12\x1d\n" +
	"\x19RELATIONSHIP_TYPE_MANAGES\x10\x05\x12\x1f\n" +
	"\x1bRELATIONSHIP_TYPE_MEMBER_OF\x10\x06B@Z>github.com/omniviewdev/plugin-sdk/proto/v1/resource;resourcepbb\x06proto3"

var (
	file_proto_v1_resource_relationship_proto_rawDescOnce sync.Once
	file_proto_v1_resource_relationship_proto_rawDescData []byte
)

func file_proto_v1_resource_relationship_proto_rawDescGZIP() []byte {
	file_proto_v1_resource_relationship_proto_rawDescOnce.Do(func() {
		file_proto_v1_resource_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_resource_relationship_proto_rawDesc), len(file_proto_v1_resource_relationship_proto_rawDesc)))
	})
	return file_proto_v1_resource_relationship_proto_rawDescData
}

var file_proto_v1_resource_relationship_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_resource_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_v1_resource_relationship_proto_goTypes = []any{
	(RelationshipType)(0),                // 0: omniview.sdk.resource.v1.RelationshipType
	(*RelationshipDescriptor)(nil),       // 1: omniview.sdk.resource.v1.RelationshipDescriptor
	(*RelationshipExtractor)(nil),        // 2: omniview.sdk.resource.v1.RelationshipExtractor
	(*ResourceRef)(nil),                  // 3: omniview.sdk.resource.v1.ResourceRef
	(*ResolvedRelationship)(nil),         // 4: omniview.sdk.resource.v1.ResolvedRelationship
	(*RelationshipEdge)(nil),             // 5: omniview.sdk.resource.v1.RelationshipEdge
	(*DependencyTree)(nil),               // 6: omniview.sdk.resource.v1.DependencyTree
	(*DependencyNode)(nil),               // 7: omniview.sdk.resource.v1.DependencyNode
	(*RelationshipsRequest)(nil),         // 8: omniview.sdk.resource.v1.RelationshipsRequest
	(*RelationshipsResponse)(nil),        // 9: omniview.sdk.resource.v1.RelationshipsResponse
	(*ResolveRelationshipsRequest)(nil),  // 10: omniview.sdk.resource.v1.ResolveRelationshipsRequest
	(*ResolveRelationshipsResponse)(nil), // 11: omniview.sdk.resource.v1.ResolveRelationshipsResponse
	nil,                                  // 12: omniview.sdk.resource.v1.RelationshipExtractor.LabelSelectorEntry
}
var file_proto_v1_resource_relationship_proto_depIdxs = []int32{
	0,  // 0: omniview.sdk.resource.v1.RelationshipDescriptor.type:type_name -> omniview.sdk.resource.v1.RelationshipType
	2,  // 1: omniview.sdk.resource.v1.RelationshipDescriptor.extractor:type_name -> omniview.sdk.resource.v1.RelationshipExtractor
	12, // 2: omniview.sdk.resource.v1.RelationshipExtractor.label_selector:type_name -> omniview.sdk.resource.v1.RelationshipExtractor.LabelSelectorEntry
	1,  // 3: omniview.sdk.resource.v1.ResolvedRelationship.descriptor:type_name -> omniview.sdk.resource.v1.RelationshipDescriptor
	3,  // 4: omniview.sdk.resource.v1.ResolvedRelationship.targets:type_name -> omniview.sdk.resource.v1.ResourceRef
	3,  // 5: omniview.sdk.resource.v1.RelationshipEdge.source:type_name -> omniview.sdk.resource.v1.ResourceRef
	3,  // 6: omniview.sdk.resource.v1.RelationshipEdge.target:type_name -> omniview.sdk.resource.v1.ResourceRef
	1,  // 7: omniview.sdk.resource.v1.RelationshipEdge.descriptor:type_name -> omniview.sdk.resource.v1.RelationshipDescriptor
	3,  // 8: omniview.sdk.resource.v1.DependencyTree.root:type_name -> omniview.sdk.resource.v1.ResourceRef
	7,  // 9: omniview.sdk.resource.v1.DependencyTree.children:type_name -> omniview.sdk.resource.v1.DependencyNode
	5,  // 10: omniview.sdk.resource.v1.DependencyNode.edge:type_name -> omniview.sdk.resource.v1.RelationshipEdge
	7,  // 11: omniview.sdk.resource.v1.DependencyNode.children:type_name -> omniview.sdk.resource.v1.DependencyNode
	1,  // 12: omniview.sdk.resource.v1.RelationshipsResponse.relationships:type_name -> omniview.sdk.resource.v1.RelationshipDescriptor
	4,  // 13: omniview.sdk.resource.v1.ResolveRelationshipsResponse.relationships:type_name -> omniview.sdk.resource.v1.ResolvedRelationship
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_resource_relationship_proto_init() }
func file_proto_v1_resource_relationship_proto_init() {
	if File_proto_v1_resource_relationship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_resource_relationship_proto_rawDesc), len(file_proto_v1_resource_relationship_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_resource_relationship_proto_goTypes,
		DependencyIndexes: file_proto_v1_resource_relationship_proto_depIdxs,
		EnumInfos:         file_proto_v1_resource_relationship_proto_enumTypes,
		MessageInfos:      file_proto_v1_resource_relationship_proto_msgTypes,
	}.Build()
	File_proto_v1_resource_relationship_proto = out.File
	file_proto_v1_resource_relationship_proto_goTypes = nil
	file_proto_v1_resource_relationship_proto_depIdxs = nil
}
