// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/v1/resource/resource.proto

package resourcepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ResourcePlugin_LoadConnections_FullMethodName         = "/omniview.sdk.resource.v1.ResourcePlugin/LoadConnections"
	ResourcePlugin_StartConnection_FullMethodName         = "/omniview.sdk.resource.v1.ResourcePlugin/StartConnection"
	ResourcePlugin_StopConnection_FullMethodName          = "/omniview.sdk.resource.v1.ResourcePlugin/StopConnection"
	ResourcePlugin_GetConnectionNamespaces_FullMethodName = "/omniview.sdk.resource.v1.ResourcePlugin/GetConnectionNamespaces"
	ResourcePlugin_Get_FullMethodName                     = "/omniview.sdk.resource.v1.ResourcePlugin/Get"
	ResourcePlugin_List_FullMethodName                    = "/omniview.sdk.resource.v1.ResourcePlugin/List"
	ResourcePlugin_Find_FullMethodName                    = "/omniview.sdk.resource.v1.ResourcePlugin/Find"
	ResourcePlugin_Create_FullMethodName                  = "/omniview.sdk.resource.v1.ResourcePlugin/Create"
	ResourcePlugin_Update_FullMethodName                  = "/omniview.sdk.resource.v1.ResourcePlugin/Update"
	ResourcePlugin_Delete_FullMethodName                  = "/omniview.sdk.resource.v1.ResourcePlugin/Delete"
	ResourcePlugin_GetResourceGroups_FullMethodName       = "/omniview.sdk.resource.v1.ResourcePlugin/GetResourceGroups"
	ResourcePlugin_GetResourceTypes_FullMethodName        = "/omniview.sdk.resource.v1.ResourcePlugin/GetResourceTypes"
	ResourcePlugin_GetResourceCapabilities_FullMethodName = "/omniview.sdk.resource.v1.ResourcePlugin/GetResourceCapabilities"
	ResourcePlugin_GetFilterFields_FullMethodName         = "/omniview.sdk.resource.v1.ResourcePlugin/GetFilterFields"
	ResourcePlugin_GetResourceSchema_FullMethodName       = "/omniview.sdk.resource.v1.ResourcePlugin/GetResourceSchema"
	ResourcePlugin_GetEditorSchemas_FullMethodName        = "/omniview.sdk.resource.v1.ResourcePlugin/GetEditorSchemas"
	ResourcePlugin_GetActions_FullMethodName              = "/omniview.sdk.resource.v1.ResourcePlugin/GetActions"
	ResourcePlugin_ExecuteAction_FullMethodName           = "/omniview.sdk.resource.v1.ResourcePlugin/ExecuteAction"
	ResourcePlugin_StreamAction_FullMethodName            = "/omniview.sdk.resource.v1.ResourcePlugin/StreamAction"
	ResourcePlugin_ListenForEvents_FullMethodName         = "/omniview.sdk.resource.v1.ResourcePlugin/ListenForEvents"
	ResourcePlugin_EnsureResourceWatch_FullMethodName     = "/omniview.sdk.resource.v1.ResourcePlugin/EnsureResourceWatch"
	ResourcePlugin_StopResourceWatch_FullMethodName       = "/omniview.sdk.resource.v1.ResourcePlugin/StopResourceWatch"
	ResourcePlugin_WatchConnections_FullMethodName        = "/omniview.sdk.resource.v1.ResourcePlugin/WatchConnections"
	ResourcePlugin_GetWatchState_FullMethodName           = "/omniview.sdk.resource.v1.ResourcePlugin/GetWatchState"
	ResourcePlugin_GetRelationships_FullMethodName        = "/omniview.sdk.resource.v1.ResourcePlugin/GetRelationships"
	ResourcePlugin_ResolveRelationships_FullMethodName    = "/omniview.sdk.resource.v1.ResourcePlugin/ResolveRelationships"
	ResourcePlugin_GetHealth_FullMethodName               = "/omniview.sdk.resource.v1.ResourcePlugin/GetHealth"
	ResourcePlugin_GetResourceEvents_FullMethodName       = "/omniview.sdk.resource.v1.ResourcePlugin/GetResourceEvents"
)

// ResourcePluginClient is the client API for ResourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourcePluginClient interface {
	// Connection lifecycle
	LoadConnections(ctx context.Context, in *LoadConnectionsRequest, opts ...grpc.CallOption) (*LoadConnectionsResponse, error)
	StartConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionStatusResponse, error)
	StopConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	GetConnectionNamespaces(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*NamespacesResponse, error)
	// CRUD
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Type information
	GetResourceGroups(ctx context.Context, in *ResourceGroupsRequest, opts ...grpc.CallOption) (*ResourceGroupsResponse, error)
	GetResourceTypes(ctx context.Context, in *ResourceTypesRequest, opts ...grpc.CallOption) (*ResourceTypesResponse, error)
	GetResourceCapabilities(ctx context.Context, in *ResourceCapabilitiesRequest, opts ...grpc.CallOption) (*ResourceCapabilitiesResponse, error)
	GetFilterFields(ctx context.Context, in *FilterFieldsRequest, opts ...grpc.CallOption) (*FilterFieldsResponse, error)
	GetResourceSchema(ctx context.Context, in *ResourceSchemaRequest, opts ...grpc.CallOption) (*ResourceSchemaResponse, error)
	GetEditorSchemas(ctx context.Context, in *EditorSchemasRequest, opts ...grpc.CallOption) (*EditorSchemasResponse, error)
	// Actions
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error)
	ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ExecuteActionResponse, error)
	StreamAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (ResourcePlugin_StreamActionClient, error)
	// Watch
	ListenForEvents(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (ResourcePlugin_ListenForEventsClient, error)
	EnsureResourceWatch(ctx context.Context, in *WatchResourceRequest, opts ...grpc.CallOption) (*WatchResourceResponse, error)
	StopResourceWatch(ctx context.Context, in *WatchResourceRequest, opts ...grpc.CallOption) (*WatchResourceResponse, error)
	WatchConnections(ctx context.Context, in *WatchConnectionsRequest, opts ...grpc.CallOption) (ResourcePlugin_WatchConnectionsClient, error)
	GetWatchState(ctx context.Context, in *GetWatchStateRequest, opts ...grpc.CallOption) (*GetWatchStateResponse, error)
	// Relationships
	GetRelationships(ctx context.Context, in *RelationshipsRequest, opts ...grpc.CallOption) (*RelationshipsResponse, error)
	ResolveRelationships(ctx context.Context, in *ResolveRelationshipsRequest, opts ...grpc.CallOption) (*ResolveRelationshipsResponse, error)
	// Health
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetResourceEvents(ctx context.Context, in *ResourceEventsRequest, opts ...grpc.CallOption) (*ResourceEventsResponse, error)
}

type resourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewResourcePluginClient(cc grpc.ClientConnInterface) ResourcePluginClient {
	return &resourcePluginClient{cc}
}

func (c *resourcePluginClient) LoadConnections(ctx context.Context, in *LoadConnectionsRequest, opts ...grpc.CallOption) (*LoadConnectionsResponse, error) {
	out := new(LoadConnectionsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_LoadConnections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) StartConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionStatusResponse, error) {
	out := new(ConnectionStatusResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_StartConnection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) StopConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_StopConnection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetConnectionNamespaces(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*NamespacesResponse, error) {
	out := new(NamespacesResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetConnectionNamespaces_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_Find_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetResourceGroups(ctx context.Context, in *ResourceGroupsRequest, opts ...grpc.CallOption) (*ResourceGroupsResponse, error) {
	out := new(ResourceGroupsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetResourceGroups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetResourceTypes(ctx context.Context, in *ResourceTypesRequest, opts ...grpc.CallOption) (*ResourceTypesResponse, error) {
	out := new(ResourceTypesResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetResourceTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetResourceCapabilities(ctx context.Context, in *ResourceCapabilitiesRequest, opts ...grpc.CallOption) (*ResourceCapabilitiesResponse, error) {
	out := new(ResourceCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetResourceCapabilities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetFilterFields(ctx context.Context, in *FilterFieldsRequest, opts ...grpc.CallOption) (*FilterFieldsResponse, error) {
	out := new(FilterFieldsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetFilterFields_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetResourceSchema(ctx context.Context, in *ResourceSchemaRequest, opts ...grpc.CallOption) (*ResourceSchemaResponse, error) {
	out := new(ResourceSchemaResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetResourceSchema_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetEditorSchemas(ctx context.Context, in *EditorSchemasRequest, opts ...grpc.CallOption) (*EditorSchemasResponse, error) {
	out := new(EditorSchemasResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetEditorSchemas_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error) {
	out := new(GetActionsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetActions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ExecuteActionResponse, error) {
	out := new(ExecuteActionResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_ExecuteAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) StreamAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (ResourcePlugin_StreamActionClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResourcePlugin_ServiceDesc.Streams[0], ResourcePlugin_StreamAction_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resourcePluginStreamActionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourcePlugin_StreamActionClient interface {
	Recv() (*StreamActionEvent, error)
	grpc.ClientStream
}

type resourcePluginStreamActionClient struct {
	grpc.ClientStream
}

func (x *resourcePluginStreamActionClient) Recv() (*StreamActionEvent, error) {
	m := new(StreamActionEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resourcePluginClient) ListenForEvents(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (ResourcePlugin_ListenForEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResourcePlugin_ServiceDesc.Streams[1], ResourcePlugin_ListenForEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resourcePluginListenForEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourcePlugin_ListenForEventsClient interface {
	Recv() (*WatchEvent, error)
	grpc.ClientStream
}

type resourcePluginListenForEventsClient struct {
	grpc.ClientStream
}

func (x *resourcePluginListenForEventsClient) Recv() (*WatchEvent, error) {
	m := new(WatchEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resourcePluginClient) EnsureResourceWatch(ctx context.Context, in *WatchResourceRequest, opts ...grpc.CallOption) (*WatchResourceResponse, error) {
	out := new(WatchResourceResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_EnsureResourceWatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) StopResourceWatch(ctx context.Context, in *WatchResourceRequest, opts ...grpc.CallOption) (*WatchResourceResponse, error) {
	out := new(WatchResourceResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_StopResourceWatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) WatchConnections(ctx context.Context, in *WatchConnectionsRequest, opts ...grpc.CallOption) (ResourcePlugin_WatchConnectionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResourcePlugin_ServiceDesc.Streams[2], ResourcePlugin_WatchConnections_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resourcePluginWatchConnectionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourcePlugin_WatchConnectionsClient interface {
	Recv() (*WatchConnectionsResponse, error)
	grpc.ClientStream
}

type resourcePluginWatchConnectionsClient struct {
	grpc.ClientStream
}

func (x *resourcePluginWatchConnectionsClient) Recv() (*WatchConnectionsResponse, error) {
	m := new(WatchConnectionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resourcePluginClient) GetWatchState(ctx context.Context, in *GetWatchStateRequest, opts ...grpc.CallOption) (*GetWatchStateResponse, error) {
	out := new(GetWatchStateResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetWatchState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetRelationships(ctx context.Context, in *RelationshipsRequest, opts ...grpc.CallOption) (*RelationshipsResponse, error) {
	out := new(RelationshipsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetRelationships_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) ResolveRelationships(ctx context.Context, in *ResolveRelationshipsRequest, opts ...grpc.CallOption) (*ResolveRelationshipsResponse, error) {
	out := new(ResolveRelationshipsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_ResolveRelationships_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcePluginClient) GetResourceEvents(ctx context.Context, in *ResourceEventsRequest, opts ...grpc.CallOption) (*ResourceEventsResponse, error) {
	out := new(ResourceEventsResponse)
	err := c.cc.Invoke(ctx, ResourcePlugin_GetResourceEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourcePluginServer is the server API for ResourcePlugin service.
// All implementations should embed UnimplementedResourcePluginServer
// for forward compatibility
type ResourcePluginServer interface {
	// Connection lifecycle
	LoadConnections(context.Context, *LoadConnectionsRequest) (*LoadConnectionsResponse, error)
	StartConnection(context.Context, *ConnectionRequest) (*ConnectionStatusResponse, error)
	StopConnection(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	GetConnectionNamespaces(context.Context, *ConnectionRequest) (*NamespacesResponse, error)
	// CRUD
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Type information
	GetResourceGroups(context.Context, *ResourceGroupsRequest) (*ResourceGroupsResponse, error)
	GetResourceTypes(context.Context, *ResourceTypesRequest) (*ResourceTypesResponse, error)
	GetResourceCapabilities(context.Context, *ResourceCapabilitiesRequest) (*ResourceCapabilitiesResponse, error)
	GetFilterFields(context.Context, *FilterFieldsRequest) (*FilterFieldsResponse, error)
	GetResourceSchema(context.Context, *ResourceSchemaRequest) (*ResourceSchemaResponse, error)
	GetEditorSchemas(context.Context, *EditorSchemasRequest) (*EditorSchemasResponse, error)
	// Actions
	GetActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error)
	ExecuteAction(context.Context, *ExecuteActionRequest) (*ExecuteActionResponse, error)
	StreamAction(*ExecuteActionRequest, ResourcePlugin_StreamActionServer) error
	// Watch
	ListenForEvents(*ListenRequest, ResourcePlugin_ListenForEventsServer) error
	EnsureResourceWatch(context.Context, *WatchResourceRequest) (*WatchResourceResponse, error)
	StopResourceWatch(context.Context, *WatchResourceRequest) (*WatchResourceResponse, error)
	WatchConnections(*WatchConnectionsRequest, ResourcePlugin_WatchConnectionsServer) error
	GetWatchState(context.Context, *GetWatchStateRequest) (*GetWatchStateResponse, error)
	// Relationships
	GetRelationships(context.Context, *RelationshipsRequest) (*RelationshipsResponse, error)
	ResolveRelationships(context.Context, *ResolveRelationshipsRequest) (*ResolveRelationshipsResponse, error)
	// Health
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	GetResourceEvents(context.Context, *ResourceEventsRequest) (*ResourceEventsResponse, error)
}

// UnimplementedResourcePluginServer should be embedded to have forward compatible implementations.
type UnimplementedResourcePluginServer struct {
}

func (UnimplementedResourcePluginServer) LoadConnections(context.Context, *LoadConnectionsRequest) (*LoadConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadConnections not implemented")
}
func (UnimplementedResourcePluginServer) StartConnection(context.Context, *ConnectionRequest) (*ConnectionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartConnection not implemented")
}
func (UnimplementedResourcePluginServer) StopConnection(context.Context, *ConnectionRequest) (*ConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopConnection not implemented")
}
func (UnimplementedResourcePluginServer) GetConnectionNamespaces(context.Context, *ConnectionRequest) (*NamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectionNamespaces not implemented")
}
func (UnimplementedResourcePluginServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedResourcePluginServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedResourcePluginServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedResourcePluginServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedResourcePluginServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedResourcePluginServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedResourcePluginServer) GetResourceGroups(context.Context, *ResourceGroupsRequest) (*ResourceGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceGroups not implemented")
}
func (UnimplementedResourcePluginServer) GetResourceTypes(context.Context, *ResourceTypesRequest) (*ResourceTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceTypes not implemented")
}
func (UnimplementedResourcePluginServer) GetResourceCapabilities(context.Context, *ResourceCapabilitiesRequest) (*ResourceCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceCapabilities not implemented")
}
func (UnimplementedResourcePluginServer) GetFilterFields(context.Context, *FilterFieldsRequest) (*FilterFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilterFields not implemented")
}
func (UnimplementedResourcePluginServer) GetResourceSchema(context.Context, *ResourceSchemaRequest) (*ResourceSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceSchema not implemented")
}
func (UnimplementedResourcePluginServer) GetEditorSchemas(context.Context, *EditorSchemasRequest) (*EditorSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEditorSchemas not implemented")
}
func (UnimplementedResourcePluginServer) GetActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActions not implemented")
}
func (UnimplementedResourcePluginServer) ExecuteAction(context.Context, *ExecuteActionRequest) (*ExecuteActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedResourcePluginServer) StreamAction(*ExecuteActionRequest, ResourcePlugin_StreamActionServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAction not implemented")
}
func (UnimplementedResourcePluginServer) ListenForEvents(*ListenRequest, ResourcePlugin_ListenForEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListenForEvents not implemented")
}
func (UnimplementedResourcePluginServer) EnsureResourceWatch(context.Context, *WatchResourceRequest) (*WatchResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureResourceWatch not implemented")
}
func (UnimplementedResourcePluginServer) StopResourceWatch(context.Context, *WatchResourceRequest) (*WatchResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopResourceWatch not implemented")
}
func (UnimplementedResourcePluginServer) WatchConnections(*WatchConnectionsRequest, ResourcePlugin_WatchConnectionsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchConnections not implemented")
}
func (UnimplementedResourcePluginServer) GetWatchState(context.Context, *GetWatchStateRequest) (*GetWatchStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWatchState not implemented")
}
func (UnimplementedResourcePluginServer) GetRelationships(context.Context, *RelationshipsRequest) (*RelationshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRelationships not implemented")
}
func (UnimplementedResourcePluginServer) ResolveRelationships(context.Context, *ResolveRelationshipsRequest) (*ResolveRelationshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveRelationships not implemented")
}
func (UnimplementedResourcePluginServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedResourcePluginServer) GetResourceEvents(context.Context, *ResourceEventsRequest) (*ResourceEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceEvents not implemented")
}

// UnsafeResourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourcePluginServer will
// result in compilation errors.
type UnsafeResourcePluginServer interface {
	mustEmbedUnimplementedResourcePluginServer()
}

func RegisterResourcePluginServer(s grpc.ServiceRegistrar, srv ResourcePluginServer) {
	s.RegisterService(&ResourcePlugin_ServiceDesc, srv)
}

func _ResourcePlugin_LoadConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).LoadConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_LoadConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).LoadConnections(ctx, req.(*LoadConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_StartConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).StartConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_StartConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).StartConnection(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_StopConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).StopConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_StopConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).StopConnection(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetConnectionNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetConnectionNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetConnectionNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetConnectionNamespaces(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetResourceGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetResourceGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetResourceGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetResourceGroups(ctx, req.(*ResourceGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetResourceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetResourceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetResourceTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetResourceTypes(ctx, req.(*ResourceTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetResourceCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetResourceCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetResourceCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetResourceCapabilities(ctx, req.(*ResourceCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetFilterFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetFilterFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetFilterFields_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetFilterFields(ctx, req.(*FilterFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetResourceSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetResourceSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetResourceSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetResourceSchema(ctx, req.(*ResourceSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetEditorSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditorSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetEditorSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetEditorSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetEditorSchemas(ctx, req.(*EditorSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetActions(ctx, req.(*GetActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).ExecuteAction(ctx, req.(*ExecuteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_StreamAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteActionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourcePluginServer).StreamAction(m, &resourcePluginStreamActionServer{stream})
}

type ResourcePlugin_StreamActionServer interface {
	Send(*StreamActionEvent) error
	grpc.ServerStream
}

type resourcePluginStreamActionServer struct {
	grpc.ServerStream
}

func (x *resourcePluginStreamActionServer) Send(m *StreamActionEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ResourcePlugin_ListenForEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourcePluginServer).ListenForEvents(m, &resourcePluginListenForEventsServer{stream})
}

type ResourcePlugin_ListenForEventsServer interface {
	Send(*WatchEvent) error
	grpc.ServerStream
}

type resourcePluginListenForEventsServer struct {
	grpc.ServerStream
}

func (x *resourcePluginListenForEventsServer) Send(m *WatchEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ResourcePlugin_EnsureResourceWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).EnsureResourceWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_EnsureResourceWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).EnsureResourceWatch(ctx, req.(*WatchResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_StopResourceWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).StopResourceWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_StopResourceWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).StopResourceWatch(ctx, req.(*WatchResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_WatchConnections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConnectionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourcePluginServer).WatchConnections(m, &resourcePluginWatchConnectionsServer{stream})
}

type ResourcePlugin_WatchConnectionsServer interface {
	Send(*WatchConnectionsResponse) error
	grpc.ServerStream
}

type resourcePluginWatchConnectionsServer struct {
	grpc.ServerStream
}

func (x *resourcePluginWatchConnectionsServer) Send(m *WatchConnectionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ResourcePlugin_GetWatchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetWatchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetWatchState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetWatchState(ctx, req.(*GetWatchStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetRelationships(ctx, req.(*RelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_ResolveRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).ResolveRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_ResolveRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).ResolveRelationships(ctx, req.(*ResolveRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcePlugin_GetResourceEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcePluginServer).GetResourceEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourcePlugin_GetResourceEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcePluginServer).GetResourceEvents(ctx, req.(*ResourceEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourcePlugin_ServiceDesc is the grpc.ServiceDesc for ResourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omniview.sdk.resource.v1.ResourcePlugin",
	HandlerType: (*ResourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadConnections",
			Handler:    _ResourcePlugin_LoadConnections_Handler,
		},
		{
			MethodName: "StartConnection",
			Handler:    _ResourcePlugin_StartConnection_Handler,
		},
		{
			MethodName: "StopConnection",
			Handler:    _ResourcePlugin_StopConnection_Handler,
		},
		{
			MethodName: "GetConnectionNamespaces",
			Handler:    _ResourcePlugin_GetConnectionNamespaces_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ResourcePlugin_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ResourcePlugin_List_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ResourcePlugin_Find_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ResourcePlugin_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ResourcePlugin_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ResourcePlugin_Delete_Handler,
		},
		{
			MethodName: "GetResourceGroups",
			Handler:    _ResourcePlugin_GetResourceGroups_Handler,
		},
		{
			MethodName: "GetResourceTypes",
			Handler:    _ResourcePlugin_GetResourceTypes_Handler,
		},
		{
			MethodName: "GetResourceCapabilities",
			Handler:    _ResourcePlugin_GetResourceCapabilities_Handler,
		},
		{
			MethodName: "GetFilterFields",
			Handler:    _ResourcePlugin_GetFilterFields_Handler,
		},
		{
			MethodName: "GetResourceSchema",
			Handler:    _ResourcePlugin_GetResourceSchema_Handler,
		},
		{
			MethodName: "GetEditorSchemas",
			Handler:    _ResourcePlugin_GetEditorSchemas_Handler,
		},
		{
			MethodName: "GetActions",
			Handler:    _ResourcePlugin_GetActions_Handler,
		},
		{
			MethodName: "ExecuteAction",
			Handler:    _ResourcePlugin_ExecuteAction_Handler,
		},
		{
			MethodName: "EnsureResourceWatch",
			Handler:    _ResourcePlugin_EnsureResourceWatch_Handler,
		},
		{
			MethodName: "StopResourceWatch",
			Handler:    _ResourcePlugin_StopResourceWatch_Handler,
		},
		{
			MethodName: "GetWatchState",
			Handler:    _ResourcePlugin_GetWatchState_Handler,
		},
		{
			MethodName: "GetRelationships",
			Handler:    _ResourcePlugin_GetRelationships_Handler,
		},
		{
			MethodName: "ResolveRelationships",
			Handler:    _ResourcePlugin_ResolveRelationships_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _ResourcePlugin_GetHealth_Handler,
		},
		{
			MethodName: "GetResourceEvents",
			Handler:    _ResourcePlugin_GetResourceEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAction",
			Handler:       _ResourcePlugin_StreamAction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListenForEvents",
			Handler:       _ResourcePlugin_ListenForEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchConnections",
			Handler:       _ResourcePlugin_WatchConnections_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/resource/resource.proto",
}
