// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/resource/watch.proto

package resourcepb

import (
	common "github.com/omniviewdev/plugin-sdk/proto/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchState represents the synchronization state of a resource watch.
type WatchState int32

const (
	WatchState_WATCH_STATE_UNSPECIFIED WatchState = 0
	WatchState_WATCH_STATE_SYNCING     WatchState = 1
	WatchState_WATCH_STATE_SYNCED      WatchState = 2
	WatchState_WATCH_STATE_ERROR       WatchState = 3
	WatchState_WATCH_STATE_FAILED      WatchState = 4
	WatchState_WATCH_STATE_STOPPED     WatchState = 5
)

// Enum value maps for WatchState.
var (
	WatchState_name = map[int32]string{
		0: "WATCH_STATE_UNSPECIFIED",
		1: "WATCH_STATE_SYNCING",
		2: "WATCH_STATE_SYNCED",
		3: "WATCH_STATE_ERROR",
		4: "WATCH_STATE_FAILED",
		5: "WATCH_STATE_STOPPED",
	}
	WatchState_value = map[string]int32{
		"WATCH_STATE_UNSPECIFIED": 0,
		"WATCH_STATE_SYNCING":     1,
		"WATCH_STATE_SYNCED":      2,
		"WATCH_STATE_ERROR":       3,
		"WATCH_STATE_FAILED":      4,
		"WATCH_STATE_STOPPED":     5,
	}
)

func (x WatchState) Enum() *WatchState {
	p := new(WatchState)
	*p = x
	return p
}

func (x WatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_resource_watch_proto_enumTypes[0].Descriptor()
}

func (WatchState) Type() protoreflect.EnumType {
	return &file_proto_v1_resource_watch_proto_enumTypes[0]
}

func (x WatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchState.Descriptor instead.
func (WatchState) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{0}
}

// WatchEvent is the unified event type sent over the ListenForEvents stream.
type WatchEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey  string                 `protobuf:"bytes,2,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchEvent_Add
	//	*WatchEvent_Update
	//	*WatchEvent_Delete
	//	*WatchEvent_State
	Event         isWatchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchEvent) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WatchEvent) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *WatchEvent) GetEvent() isWatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchEvent) GetAdd() *WatchAddPayload {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Add); ok {
			return x.Add
		}
	}
	return nil
}

func (x *WatchEvent) GetUpdate() *WatchUpdatePayload {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *WatchEvent) GetDelete() *WatchDeletePayload {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *WatchEvent) GetState() *WatchStateEvent {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_State); ok {
			return x.State
		}
	}
	return nil
}

type isWatchEvent_Event interface {
	isWatchEvent_Event()
}

type WatchEvent_Add struct {
	Add *WatchAddPayload `protobuf:"bytes,10,opt,name=add,proto3,oneof"`
}

type WatchEvent_Update struct {
	Update *WatchUpdatePayload `protobuf:"bytes,11,opt,name=update,proto3,oneof"`
}

type WatchEvent_Delete struct {
	Delete *WatchDeletePayload `protobuf:"bytes,12,opt,name=delete,proto3,oneof"`
}

type WatchEvent_State struct {
	State *WatchStateEvent `protobuf:"bytes,13,opt,name=state,proto3,oneof"`
}

func (*WatchEvent_Add) isWatchEvent_Event() {}

func (*WatchEvent_Update) isWatchEvent_Event() {}

func (*WatchEvent_Delete) isWatchEvent_Event() {}

func (*WatchEvent_State) isWatchEvent_Event() {}

// WatchAddPayload — a resource was added.
type WatchAddPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAddPayload) Reset() {
	*x = WatchAddPayload{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAddPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAddPayload) ProtoMessage() {}

func (x *WatchAddPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAddPayload.ProtoReflect.Descriptor instead.
func (*WatchAddPayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchAddPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchAddPayload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchAddPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WatchUpdatePayload — a resource was modified.
// Only carries the new state. OldData dropped to halve wire cost (doc 12).
type WatchUpdatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchUpdatePayload) Reset() {
	*x = WatchUpdatePayload{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchUpdatePayload) ProtoMessage() {}

func (x *WatchUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchUpdatePayload.ProtoReflect.Descriptor instead.
func (*WatchUpdatePayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{2}
}

func (x *WatchUpdatePayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchUpdatePayload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchUpdatePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WatchDeletePayload — a resource was deleted.
type WatchDeletePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDeletePayload) Reset() {
	*x = WatchDeletePayload{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDeletePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDeletePayload) ProtoMessage() {}

func (x *WatchDeletePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDeletePayload.ProtoReflect.Descriptor instead.
func (*WatchDeletePayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{3}
}

func (x *WatchDeletePayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchDeletePayload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchDeletePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WatchStateEvent — watch state changed for a resource type.
type WatchStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         WatchState             `protobuf:"varint,1,opt,name=state,proto3,enum=omniview.sdk.resource.v1.WatchState" json:"state,omitempty"`
	ResourceCount int32                  `protobuf:"varint,2,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStateEvent) Reset() {
	*x = WatchStateEvent{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStateEvent) ProtoMessage() {}

func (x *WatchStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStateEvent.ProtoReflect.Descriptor instead.
func (*WatchStateEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{4}
}

func (x *WatchStateEvent) GetState() WatchState {
	if x != nil {
		return x.State
	}
	return WatchState_WATCH_STATE_UNSPECIFIED
}

func (x *WatchStateEvent) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *WatchStateEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ListenRequest starts the event stream.
type ListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{5}
}

// WatchResourceRequest asks the plugin to start/stop watching a specific resource type.
type WatchResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,2,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResourceRequest) Reset() {
	*x = WatchResourceRequest{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResourceRequest) ProtoMessage() {}

func (x *WatchResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResourceRequest.ProtoReflect.Descriptor instead.
func (*WatchResourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{6}
}

func (x *WatchResourceRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WatchResourceRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

// WatchResourceResponse confirms the watch operation.
type WatchResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResourceResponse) Reset() {
	*x = WatchResourceResponse{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResourceResponse) ProtoMessage() {}

func (x *WatchResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResourceResponse.ProtoReflect.Descriptor instead.
func (*WatchResourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{7}
}

func (x *WatchResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WatchResourceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// WatchConnectionsRequest starts the connection change stream.
type WatchConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConnectionsRequest) Reset() {
	*x = WatchConnectionsRequest{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConnectionsRequest) ProtoMessage() {}

func (x *WatchConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConnectionsRequest.ProtoReflect.Descriptor instead.
func (*WatchConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{8}
}

// WatchConnectionsResponse is sent whenever the set of connections changes.
type WatchConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*common.Connection   `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConnectionsResponse) Reset() {
	*x = WatchConnectionsResponse{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConnectionsResponse) ProtoMessage() {}

func (x *WatchConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConnectionsResponse.ProtoReflect.Descriptor instead.
func (*WatchConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{9}
}

func (x *WatchConnectionsResponse) GetConnections() []*common.Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

// GetWatchStateRequest asks for the current watch state summary for a connection.
type GetWatchStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchStateRequest) Reset() {
	*x = GetWatchStateRequest{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchStateRequest) ProtoMessage() {}

func (x *GetWatchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchStateRequest.ProtoReflect.Descriptor instead.
func (*GetWatchStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{10}
}

func (x *GetWatchStateRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// GetWatchStateResponse returns per-resource watch states for a connection.
type GetWatchStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Resources     map[string]WatchState  `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=omniview.sdk.resource.v1.WatchState"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchStateResponse) Reset() {
	*x = GetWatchStateResponse{}
	mi := &file_proto_v1_resource_watch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchStateResponse) ProtoMessage() {}

func (x *GetWatchStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_resource_watch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchStateResponse.ProtoReflect.Descriptor instead.
func (*GetWatchStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_resource_watch_proto_rawDescGZIP(), []int{11}
}

func (x *GetWatchStateResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *GetWatchStateResponse) GetResources() map[string]WatchState {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_proto_v1_resource_watch_proto protoreflect.FileDescriptor

const file_proto_v1_resource_watch_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/v1/resource/watch.proto\x12\x18omniview.sdk.resource.v1\x1a\x1cproto/v1/common/common.proto\"\xef\x02\n" +
	"\n" +
	"WatchEvent\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x02 \x01(\tR\vresourceKey\x12=\n" +
	"\x03add\x18\n" +
	" \x01(\v2).omniview.sdk.resource.v1.WatchAddPayloadH\x00R\x03add\x12F\n" +
	"\x06update\x18\v \x01(\v2,.omniview.sdk.resource.v1.WatchUpdatePayloadH\x00R\x06update\x12F\n" +
	"\x06delete\x18\f \x01(\v2,.omniview.sdk.resource.v1.WatchDeletePayloadH\x00R\x06delete\x12A\n" +
	"\x05state\x18\r \x01(\v2).omniview.sdk.resource.v1.WatchStateEventH\x00R\x05stateB\a\n" +
	"\x05event\"S\n" +
	"\x0fWatchAddPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"V\n" +
	"\x12WatchUpdatePayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"V\n" +
	"\x12WatchDeletePayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x99\x01\n" +
	"\x0fWatchStateEvent\x12:\n" +
	"\x05state\x18\x01 \x01(\x0e2$.omniview.sdk.resource.v1.WatchStateR\x05state\x12%\n" +
	"\x0eresource_count\x18\x02 \x01(\x05R\rresourceCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x0f\n" +
	"\rListenRequest\"^\n" +
	"\x14WatchResourceRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x02 \x01(\tR\vresourceKey\"V\n" +
	"\x15WatchResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x19\n" +
	"\x17WatchConnectionsRequest\"`\n" +
	"\x18WatchConnectionsResponse\x12D\n" +
	"\vconnections\x18\x01 \x03(\v2\".omniview.sdk.common.v1.ConnectionR\vconnections\";\n" +
	"\x14GetWatchStateRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\xfe\x01\n" +
	"\x15GetWatchStateResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\\\n" +
	"\tresources\x18\x02 \x03(\v2>.omniview.sdk.resource.v1.GetWatchStateResponse.ResourcesEntryR\tresources\x1ab\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\x0e2$.omniview.sdk.resource.v1.WatchStateR\x05value:\x028\x01*\xa2\x01\n" +
	"\n" +
	"WatchState\x12\x1b\n" +
	"\x17WATCH_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WATCH_STATE_SYNCING\x10\x01\x12\x16\n" +
	"\x12WATCH_STATE_SYNCED\x10\x02\x12\x15\n" +
	"\x11WATCH_STATE_ERROR\x10\x03\x12\x16\n" +
	"\x12WATCH_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13WATCH_STATE_STOPPED\x10\x05B@Z>github.com/omniviewdev/plugin-sdk/proto/v1/resource;resourcepbb\x06proto3"

var (
	file_proto_v1_resource_watch_proto_rawDescOnce sync.Once
	file_proto_v1_resource_watch_proto_rawDescData []byte
)

func file_proto_v1_resource_watch_proto_rawDescGZIP() []byte {
	file_proto_v1_resource_watch_proto_rawDescOnce.Do(func() {
		file_proto_v1_resource_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_resource_watch_proto_rawDesc), len(file_proto_v1_resource_watch_proto_rawDesc)))
	})
	return file_proto_v1_resource_watch_proto_rawDescData
}

var file_proto_v1_resource_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_resource_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_v1_resource_watch_proto_goTypes = []any{
	(WatchState)(0),                  // 0: omniview.sdk.resource.v1.WatchState
	(*WatchEvent)(nil),               // 1: omniview.sdk.resource.v1.WatchEvent
	(*WatchAddPayload)(nil),          // 2: omniview.sdk.resource.v1.WatchAddPayload
	(*WatchUpdatePayload)(nil),       // 3: omniview.sdk.resource.v1.WatchUpdatePayload
	(*WatchDeletePayload)(nil),       // 4: omniview.sdk.resource.v1.WatchDeletePayload
	(*WatchStateEvent)(nil),          // 5: omniview.sdk.resource.v1.WatchStateEvent
	(*ListenRequest)(nil),            // 6: omniview.sdk.resource.v1.ListenRequest
	(*WatchResourceRequest)(nil),     // 7: omniview.sdk.resource.v1.WatchResourceRequest
	(*WatchResourceResponse)(nil),    // 8: omniview.sdk.resource.v1.WatchResourceResponse
	(*WatchConnectionsRequest)(nil),  // 9: omniview.sdk.resource.v1.WatchConnectionsRequest
	(*WatchConnectionsResponse)(nil), // 10: omniview.sdk.resource.v1.WatchConnectionsResponse
	(*GetWatchStateRequest)(nil),     // 11: omniview.sdk.resource.v1.GetWatchStateRequest
	(*GetWatchStateResponse)(nil),    // 12: omniview.sdk.resource.v1.GetWatchStateResponse
	nil,                              // 13: omniview.sdk.resource.v1.GetWatchStateResponse.ResourcesEntry
	(*common.Connection)(nil),        // 14: omniview.sdk.common.v1.Connection
}
var file_proto_v1_resource_watch_proto_depIdxs = []int32{
	2,  // 0: omniview.sdk.resource.v1.WatchEvent.add:type_name -> omniview.sdk.resource.v1.WatchAddPayload
	3,  // 1: omniview.sdk.resource.v1.WatchEvent.update:type_name -> omniview.sdk.resource.v1.WatchUpdatePayload
	4,  // 2: omniview.sdk.resource.v1.WatchEvent.delete:type_name -> omniview.sdk.resource.v1.WatchDeletePayload
	5,  // 3: omniview.sdk.resource.v1.WatchEvent.state:type_name -> omniview.sdk.resource.v1.WatchStateEvent
	0,  // 4: omniview.sdk.resource.v1.WatchStateEvent.state:type_name -> omniview.sdk.resource.v1.WatchState
	14, // 5: omniview.sdk.resource.v1.WatchConnectionsResponse.connections:type_name -> omniview.sdk.common.v1.Connection
	13, // 6: omniview.sdk.resource.v1.GetWatchStateResponse.resources:type_name -> omniview.sdk.resource.v1.GetWatchStateResponse.ResourcesEntry
	0,  // 7: omniview.sdk.resource.v1.GetWatchStateResponse.ResourcesEntry.value:type_name -> omniview.sdk.resource.v1.WatchState
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_resource_watch_proto_init() }
func file_proto_v1_resource_watch_proto_init() {
	if File_proto_v1_resource_watch_proto != nil {
		return
	}
	file_proto_v1_resource_watch_proto_msgTypes[0].OneofWrappers = []any{
		(*WatchEvent_Add)(nil),
		(*WatchEvent_Update)(nil),
		(*WatchEvent_Delete)(nil),
		(*WatchEvent_State)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_resource_watch_proto_rawDesc), len(file_proto_v1_resource_watch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_resource_watch_proto_goTypes,
		DependencyIndexes: file_proto_v1_resource_watch_proto_depIdxs,
		EnumInfos:         file_proto_v1_resource_watch_proto_enumTypes,
		MessageInfos:      file_proto_v1_resource_watch_proto_msgTypes,
	}.Build()
	File_proto_v1_resource_watch_proto = out.File
	file_proto_v1_resource_watch_proto_goTypes = nil
	file_proto_v1_resource_watch_proto_depIdxs = nil
}
