// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/lifecycle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginLifecycle_GetInfo_FullMethodName         = "/com.omniview.pluginsdk.PluginLifecycle/GetInfo"
	PluginLifecycle_GetCapabilities_FullMethodName = "/com.omniview.pluginsdk.PluginLifecycle/GetCapabilities"
	PluginLifecycle_HealthCheck_FullMethodName     = "/com.omniview.pluginsdk.PluginLifecycle/HealthCheck"
)

// PluginLifecycleClient is the client API for PluginLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginLifecycleClient interface {
	// GetInfo returns plugin identification and version information.
	GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// GetCapabilities returns the list of capabilities this plugin serves.
	// Replaces exception-based gRPC probing on the host side.
	GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// HealthCheck returns the current health status of the plugin process.
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type pluginLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginLifecycleClient(cc grpc.ClientConnInterface) PluginLifecycleClient {
	return &pluginLifecycleClient{cc}
}

func (c *pluginLifecycleClient) GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_GetInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_GetCapabilities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginLifecycleServer is the server API for PluginLifecycle service.
// All implementations should embed UnimplementedPluginLifecycleServer
// for forward compatibility
type PluginLifecycleServer interface {
	// GetInfo returns plugin identification and version information.
	GetInfo(context.Context, *emptypb.Empty) (*GetInfoResponse, error)
	// GetCapabilities returns the list of capabilities this plugin serves.
	// Replaces exception-based gRPC probing on the host side.
	GetCapabilities(context.Context, *emptypb.Empty) (*GetCapabilitiesResponse, error)
	// HealthCheck returns the current health status of the plugin process.
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
}

// UnimplementedPluginLifecycleServer should be embedded to have forward compatible implementations.
type UnimplementedPluginLifecycleServer struct {
}

func (UnimplementedPluginLifecycleServer) GetInfo(context.Context, *emptypb.Empty) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginLifecycleServer) GetCapabilities(context.Context, *emptypb.Empty) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPluginLifecycleServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

// UnsafePluginLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginLifecycleServer will
// result in compilation errors.
type UnsafePluginLifecycleServer interface {
	mustEmbedUnimplementedPluginLifecycleServer()
}

func RegisterPluginLifecycleServer(s grpc.ServiceRegistrar, srv PluginLifecycleServer) {
	s.RegisterService(&PluginLifecycle_ServiceDesc, srv)
}

func _PluginLifecycle_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).GetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).GetCapabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginLifecycle_ServiceDesc is the grpc.ServiceDesc for PluginLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.omniview.pluginsdk.PluginLifecycle",
	HandlerType: (*PluginLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginLifecycle_GetInfo_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _PluginLifecycle_GetCapabilities_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginLifecycle_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lifecycle.proto",
}
