// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/lifecycle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingStatus int32

const (
	ServingStatus_UNKNOWN     ServingStatus = 0
	ServingStatus_SERVING     ServingStatus = 1
	ServingStatus_NOT_SERVING ServingStatus = 2
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lifecycle_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_lifecycle_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PluginId           string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SdkProtocolVersion int32                  `protobuf:"varint,3,opt,name=sdk_protocol_version,json=sdkProtocolVersion,proto3" json:"sdk_protocol_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetSdkProtocolVersion() int32 {
	if x != nil {
		return x.SdkProtocolVersion
	}
	return 0
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_proto_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServingStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=com.omniview.pluginsdk.ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_UNKNOWN
}

var File_proto_lifecycle_proto protoreflect.FileDescriptor

const file_proto_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x15proto/lifecycle.proto\x12\x16com.omniview.pluginsdk\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\x0fGetInfoResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x120\n" +
	"\x14sdk_protocol_version\x18\x03 \x01(\x05R\x12sdkProtocolVersion\"=\n" +
	"\x17GetCapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"T\n" +
	"\x13HealthCheckResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.com.omniview.pluginsdk.ServingStatusR\x06status*:\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x8d\x02\n" +
	"\x0fPluginLifecycle\x12J\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a'.com.omniview.pluginsdk.GetInfoResponse\x12Z\n" +
	"\x0fGetCapabilities\x12\x16.google.protobuf.Empty\x1a/.com.omniview.pluginsdk.GetCapabilitiesResponse\x12R\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a+.com.omniview.pluginsdk.HealthCheckResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_lifecycle_proto_rawDescOnce sync.Once
	file_proto_lifecycle_proto_rawDescData []byte
)

func file_proto_lifecycle_proto_rawDescGZIP() []byte {
	file_proto_lifecycle_proto_rawDescOnce.Do(func() {
		file_proto_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lifecycle_proto_rawDesc), len(file_proto_lifecycle_proto_rawDesc)))
	})
	return file_proto_lifecycle_proto_rawDescData
}

var file_proto_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_lifecycle_proto_goTypes = []any{
	(ServingStatus)(0),              // 0: com.omniview.pluginsdk.ServingStatus
	(*GetInfoResponse)(nil),         // 1: com.omniview.pluginsdk.GetInfoResponse
	(*GetCapabilitiesResponse)(nil), // 2: com.omniview.pluginsdk.GetCapabilitiesResponse
	(*HealthCheckResponse)(nil),     // 3: com.omniview.pluginsdk.HealthCheckResponse
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
}
var file_proto_lifecycle_proto_depIdxs = []int32{
	0, // 0: com.omniview.pluginsdk.HealthCheckResponse.status:type_name -> com.omniview.pluginsdk.ServingStatus
	4, // 1: com.omniview.pluginsdk.PluginLifecycle.GetInfo:input_type -> google.protobuf.Empty
	4, // 2: com.omniview.pluginsdk.PluginLifecycle.GetCapabilities:input_type -> google.protobuf.Empty
	4, // 3: com.omniview.pluginsdk.PluginLifecycle.HealthCheck:input_type -> google.protobuf.Empty
	1, // 4: com.omniview.pluginsdk.PluginLifecycle.GetInfo:output_type -> com.omniview.pluginsdk.GetInfoResponse
	2, // 5: com.omniview.pluginsdk.PluginLifecycle.GetCapabilities:output_type -> com.omniview.pluginsdk.GetCapabilitiesResponse
	3, // 6: com.omniview.pluginsdk.PluginLifecycle.HealthCheck:output_type -> com.omniview.pluginsdk.HealthCheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lifecycle_proto_init() }
func file_proto_lifecycle_proto_init() {
	if File_proto_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lifecycle_proto_rawDesc), len(file_proto_lifecycle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lifecycle_proto_goTypes,
		DependencyIndexes: file_proto_lifecycle_proto_depIdxs,
		EnumInfos:         file_proto_lifecycle_proto_enumTypes,
		MessageInfos:      file_proto_lifecycle_proto_msgTypes,
	}.Build()
	File_proto_lifecycle_proto = out.File
	file_proto_lifecycle_proto_goTypes = nil
	file_proto_lifecycle_proto_depIdxs = nil
}
