// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/networker/networker.proto

package networkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortForwardProtocol int32

const (
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_TCP PortForwardProtocol = 0
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_UDP PortForwardProtocol = 1
)

// Enum value maps for PortForwardProtocol.
var (
	PortForwardProtocol_name = map[int32]string{
		0: "PORT_FORWARD_PROTOCOL_TCP",
		1: "PORT_FORWARD_PROTOCOL_UDP",
	}
	PortForwardProtocol_value = map[string]int32{
		"PORT_FORWARD_PROTOCOL_TCP": 0,
		"PORT_FORWARD_PROTOCOL_UDP": 1,
	}
)

func (x PortForwardProtocol) Enum() *PortForwardProtocol {
	p := new(PortForwardProtocol)
	*p = x
	return p
}

func (x PortForwardProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortForwardProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_networker_networker_proto_enumTypes[0].Descriptor()
}

func (PortForwardProtocol) Type() protoreflect.EnumType {
	return &file_proto_v1_networker_networker_proto_enumTypes[0]
}

func (x PortForwardProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortForwardProtocol.Descriptor instead.
func (PortForwardProtocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{0}
}

type PortForwardSession_SessionState int32

const (
	PortForwardSession_ACTIVE  PortForwardSession_SessionState = 0
	PortForwardSession_PAUSED  PortForwardSession_SessionState = 1
	PortForwardSession_STOPPED PortForwardSession_SessionState = 2
	PortForwardSession_FAILED  PortForwardSession_SessionState = 3
)

// Enum value maps for PortForwardSession_SessionState.
var (
	PortForwardSession_SessionState_name = map[int32]string{
		0: "ACTIVE",
		1: "PAUSED",
		2: "STOPPED",
		3: "FAILED",
	}
	PortForwardSession_SessionState_value = map[string]int32{
		"ACTIVE":  0,
		"PAUSED":  1,
		"STOPPED": 2,
		"FAILED":  3,
	}
)

func (x PortForwardSession_SessionState) Enum() *PortForwardSession_SessionState {
	p := new(PortForwardSession_SessionState)
	*p = x
	return p
}

func (x PortForwardSession_SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortForwardSession_SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_networker_networker_proto_enumTypes[1].Descriptor()
}

func (PortForwardSession_SessionState) Type() protoreflect.EnumType {
	return &file_proto_v1_networker_networker_proto_enumTypes[1]
}

func (x PortForwardSession_SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortForwardSession_SessionState.Descriptor instead.
func (PortForwardSession_SessionState) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{0, 0}
}

// An active port forwarding session that is used to forward network traffic
// from a remote resource to the local machine. Common use cases include:
// - Kubernetes port forwarding
// - AWS SSM port forwarding
// - SSH port forwarding
type PortForwardSession struct {
	state      protoimpl.MessageState          `protogen:"open.v1"`
	Id         string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalPort  int32                           `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort int32                           `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Protocol   PortForwardProtocol             `protobuf:"varint,4,opt,name=protocol,proto3,enum=omniview.sdk.networker.v1.PortForwardProtocol" json:"protocol,omitempty"`
	CreatedAt  *timestamppb.Timestamp          `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp          `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Labels     map[string]string               `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State      PortForwardSession_SessionState `protobuf:"varint,8,opt,name=state,proto3,enum=omniview.sdk.networker.v1.PortForwardSession_SessionState" json:"state,omitempty"`
	Encryption *PortForwardSessionEncryption   `protobuf:"bytes,9,opt,name=encryption,proto3" json:"encryption,omitempty"`
	// Types that are valid to be assigned to Connection:
	//
	//	*PortForwardSession_ResourceConnection
	//	*PortForwardSession_StaticConnection
	Connection    isPortForwardSession_Connection `protobuf_oneof:"connection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardSession) Reset() {
	*x = PortForwardSession{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSession) ProtoMessage() {}

func (x *PortForwardSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardSession.ProtoReflect.Descriptor instead.
func (*PortForwardSession) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{0}
}

func (x *PortForwardSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PortForwardSession) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *PortForwardSession) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *PortForwardSession) GetProtocol() PortForwardProtocol {
	if x != nil {
		return x.Protocol
	}
	return PortForwardProtocol_PORT_FORWARD_PROTOCOL_TCP
}

func (x *PortForwardSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PortForwardSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PortForwardSession) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PortForwardSession) GetState() PortForwardSession_SessionState {
	if x != nil {
		return x.State
	}
	return PortForwardSession_ACTIVE
}

func (x *PortForwardSession) GetEncryption() *PortForwardSessionEncryption {
	if x != nil {
		return x.Encryption
	}
	return nil
}

func (x *PortForwardSession) GetConnection() isPortForwardSession_Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *PortForwardSession) GetResourceConnection() *PortForwardResourceConnection {
	if x != nil {
		if x, ok := x.Connection.(*PortForwardSession_ResourceConnection); ok {
			return x.ResourceConnection
		}
	}
	return nil
}

func (x *PortForwardSession) GetStaticConnection() *PortForwardStaticConnection {
	if x != nil {
		if x, ok := x.Connection.(*PortForwardSession_StaticConnection); ok {
			return x.StaticConnection
		}
	}
	return nil
}

type isPortForwardSession_Connection interface {
	isPortForwardSession_Connection()
}

type PortForwardSession_ResourceConnection struct {
	ResourceConnection *PortForwardResourceConnection `protobuf:"bytes,20,opt,name=resource_connection,json=resourceConnection,proto3,oneof"`
}

type PortForwardSession_StaticConnection struct {
	StaticConnection *PortForwardStaticConnection `protobuf:"bytes,21,opt,name=static_connection,json=staticConnection,proto3,oneof"`
}

func (*PortForwardSession_ResourceConnection) isPortForwardSession_Connection() {}

func (*PortForwardSession_StaticConnection) isPortForwardSession_Connection() {}

// Port forwarding can happen to a resource via it's resource parameter, or via a static connection
// to a specific address and port. This message encapsulates the options for the connection
// to a resource.
type PortForwardResourceConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,4,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	ResourceData  *structpb.Struct       `protobuf:"bytes,5,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardResourceConnection) Reset() {
	*x = PortForwardResourceConnection{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardResourceConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardResourceConnection) ProtoMessage() {}

func (x *PortForwardResourceConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardResourceConnection.ProtoReflect.Descriptor instead.
func (*PortForwardResourceConnection) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{1}
}

func (x *PortForwardResourceConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *PortForwardResourceConnection) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PortForwardResourceConnection) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PortForwardResourceConnection) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *PortForwardResourceConnection) GetResourceData() *structpb.Struct {
	if x != nil {
		return x.ResourceData
	}
	return nil
}

type PortForwardStaticConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPv4 or IPv6 address
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardStaticConnection) Reset() {
	*x = PortForwardStaticConnection{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardStaticConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardStaticConnection) ProtoMessage() {}

func (x *PortForwardStaticConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardStaticConnection.ProtoReflect.Descriptor instead.
func (*PortForwardStaticConnection) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{2}
}

func (x *PortForwardStaticConnection) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PortForwardSessionEncryption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardSessionEncryption) Reset() {
	*x = PortForwardSessionEncryption{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSessionEncryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSessionEncryption) ProtoMessage() {}

func (x *PortForwardSessionEncryption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardSessionEncryption.ProtoReflect.Descriptor instead.
func (*PortForwardSessionEncryption) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{3}
}

func (x *PortForwardSessionEncryption) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PortForwardSessionEncryption) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PortForwardSessionEncryption) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Options for creating a new port forwarding session
type PortForwardSessionOptions struct {
	state      protoimpl.MessageState        `protogen:"open.v1"`
	LocalPort  int32                         `protobuf:"varint,1,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort int32                         `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Protocol   PortForwardProtocol           `protobuf:"varint,3,opt,name=protocol,proto3,enum=omniview.sdk.networker.v1.PortForwardProtocol" json:"protocol,omitempty"`
	Labels     map[string]string             `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Params     map[string]string             `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Encryption *PortForwardSessionEncryption `protobuf:"bytes,6,opt,name=encryption,proto3" json:"encryption,omitempty"`
	// Types that are valid to be assigned to Connection:
	//
	//	*PortForwardSessionOptions_ResourceConnection
	//	*PortForwardSessionOptions_StaticConnection
	Connection    isPortForwardSessionOptions_Connection `protobuf_oneof:"connection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardSessionOptions) Reset() {
	*x = PortForwardSessionOptions{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSessionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSessionOptions) ProtoMessage() {}

func (x *PortForwardSessionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardSessionOptions.ProtoReflect.Descriptor instead.
func (*PortForwardSessionOptions) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{4}
}

func (x *PortForwardSessionOptions) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *PortForwardSessionOptions) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *PortForwardSessionOptions) GetProtocol() PortForwardProtocol {
	if x != nil {
		return x.Protocol
	}
	return PortForwardProtocol_PORT_FORWARD_PROTOCOL_TCP
}

func (x *PortForwardSessionOptions) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PortForwardSessionOptions) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PortForwardSessionOptions) GetEncryption() *PortForwardSessionEncryption {
	if x != nil {
		return x.Encryption
	}
	return nil
}

func (x *PortForwardSessionOptions) GetConnection() isPortForwardSessionOptions_Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *PortForwardSessionOptions) GetResourceConnection() *PortForwardResourceConnection {
	if x != nil {
		if x, ok := x.Connection.(*PortForwardSessionOptions_ResourceConnection); ok {
			return x.ResourceConnection
		}
	}
	return nil
}

func (x *PortForwardSessionOptions) GetStaticConnection() *PortForwardStaticConnection {
	if x != nil {
		if x, ok := x.Connection.(*PortForwardSessionOptions_StaticConnection); ok {
			return x.StaticConnection
		}
	}
	return nil
}

type isPortForwardSessionOptions_Connection interface {
	isPortForwardSessionOptions_Connection()
}

type PortForwardSessionOptions_ResourceConnection struct {
	ResourceConnection *PortForwardResourceConnection `protobuf:"bytes,10,opt,name=resource_connection,json=resourceConnection,proto3,oneof"`
}

type PortForwardSessionOptions_StaticConnection struct {
	StaticConnection *PortForwardStaticConnection `protobuf:"bytes,11,opt,name=static_connection,json=staticConnection,proto3,oneof"`
}

func (*PortForwardSessionOptions_ResourceConnection) isPortForwardSessionOptions_Connection() {}

func (*PortForwardSessionOptions_StaticConnection) isPortForwardSessionOptions_Connection() {}

type PortForwardSessionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardSessionByIdRequest) Reset() {
	*x = PortForwardSessionByIdRequest{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSessionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSessionByIdRequest) ProtoMessage() {}

func (x *PortForwardSessionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardSessionByIdRequest.ProtoReflect.Descriptor instead.
func (*PortForwardSessionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{5}
}

func (x *PortForwardSessionByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindPortForwardSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPortForwardSessionRequest) Reset() {
	*x = FindPortForwardSessionRequest{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPortForwardSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPortForwardSessionRequest) ProtoMessage() {}

func (x *FindPortForwardSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPortForwardSessionRequest.ProtoReflect.Descriptor instead.
func (*FindPortForwardSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{6}
}

func (x *FindPortForwardSessionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *FindPortForwardSessionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type PortForwardSessionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PortForwardSession    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardSessionByIdResponse) Reset() {
	*x = PortForwardSessionByIdResponse{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSessionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSessionByIdResponse) ProtoMessage() {}

func (x *PortForwardSessionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardSessionByIdResponse.ProtoReflect.Descriptor instead.
func (*PortForwardSessionByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{7}
}

func (x *PortForwardSessionByIdResponse) GetSession() *PortForwardSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type PortForwardSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*PortForwardSession  `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardSessionListResponse) Reset() {
	*x = PortForwardSessionListResponse{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSessionListResponse) ProtoMessage() {}

func (x *PortForwardSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardSessionListResponse.ProtoReflect.Descriptor instead.
func (*PortForwardSessionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{8}
}

func (x *PortForwardSessionListResponse) GetSessions() []*PortForwardSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSupportedPortForwardTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []string               `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedPortForwardTargetsResponse) Reset() {
	*x = GetSupportedPortForwardTargetsResponse{}
	mi := &file_proto_v1_networker_networker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedPortForwardTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedPortForwardTargetsResponse) ProtoMessage() {}

func (x *GetSupportedPortForwardTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_networker_networker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedPortForwardTargetsResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedPortForwardTargetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_networker_networker_proto_rawDescGZIP(), []int{9}
}

func (x *GetSupportedPortForwardTargetsResponse) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_proto_v1_networker_networker_proto protoreflect.FileDescriptor

const file_proto_v1_networker_networker_proto_rawDesc = "" +
	"\n" +
	"\"proto/v1/networker/networker.proto\x12\x19omniview.sdk.networker.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\a\n" +
	"\x12PortForwardSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\x05R\n" +
	"remotePort\x12J\n" +
	"\bprotocol\x18\x04 \x01(\x0e2..omniview.sdk.networker.v1.PortForwardProtocolR\bprotocol\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12Q\n" +
	"\x06labels\x18\a \x03(\v29.omniview.sdk.networker.v1.PortForwardSession.LabelsEntryR\x06labels\x12P\n" +
	"\x05state\x18\b \x01(\x0e2:.omniview.sdk.networker.v1.PortForwardSession.SessionStateR\x05state\x12W\n" +
	"\n" +
	"encryption\x18\t \x01(\v27.omniview.sdk.networker.v1.PortForwardSessionEncryptionR\n" +
	"encryption\x12k\n" +
	"\x13resource_connection\x18\x14 \x01(\v28.omniview.sdk.networker.v1.PortForwardResourceConnectionH\x00R\x12resourceConnection\x12e\n" +
	"\x11static_connection\x18\x15 \x01(\v26.omniview.sdk.networker.v1.PortForwardStaticConnectionH\x00R\x10staticConnection\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\fSessionState\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03B\f\n" +
	"\n" +
	"connection\"\xe3\x01\n" +
	"\x1dPortForwardResourceConnection\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fresource_key\x18\x04 \x01(\tR\vresourceKey\x12<\n" +
	"\rresource_data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fresourceData\"7\n" +
	"\x1bPortForwardStaticConnection\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"h\n" +
	"\x1cPortForwardSessionEncryption\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\x8c\x06\n" +
	"\x19PortForwardSessionOptions\x12\x1d\n" +
	"\n" +
	"local_port\x18\x01 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\x05R\n" +
	"remotePort\x12J\n" +
	"\bprotocol\x18\x03 \x01(\x0e2..omniview.sdk.networker.v1.PortForwardProtocolR\bprotocol\x12X\n" +
	"\x06labels\x18\x04 \x03(\v2@.omniview.sdk.networker.v1.PortForwardSessionOptions.LabelsEntryR\x06labels\x12X\n" +
	"\x06params\x18\x05 \x03(\v2@.omniview.sdk.networker.v1.PortForwardSessionOptions.ParamsEntryR\x06params\x12W\n" +
	"\n" +
	"encryption\x18\x06 \x01(\v27.omniview.sdk.networker.v1.PortForwardSessionEncryptionR\n" +
	"encryption\x12k\n" +
	"\x13resource_connection\x18\n" +
	" \x01(\v28.omniview.sdk.networker.v1.PortForwardResourceConnectionH\x00R\x12resourceConnection\x12e\n" +
	"\x11static_connection\x18\v \x01(\v26.omniview.sdk.networker.v1.PortForwardStaticConnectionH\x00R\x10staticConnection\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"connection\"/\n" +
	"\x1dPortForwardSessionByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"e\n" +
	"\x1dFindPortForwardSessionRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\"i\n" +
	"\x1ePortForwardSessionByIdResponse\x12G\n" +
	"\asession\x18\x01 \x01(\v2-.omniview.sdk.networker.v1.PortForwardSessionR\asession\"k\n" +
	"\x1ePortForwardSessionListResponse\x12I\n" +
	"\bsessions\x18\x01 \x03(\v2-.omniview.sdk.networker.v1.PortForwardSessionR\bsessions\"F\n" +
	"&GetSupportedPortForwardTargetsResponse\x12\x1c\n" +
	"\tresources\x18\x01 \x03(\tR\tresources*S\n" +
	"\x13PortForwardProtocol\x12\x1d\n" +
	"\x19PORT_FORWARD_PROTOCOL_TCP\x10\x00\x12\x1d\n" +
	"\x19PORT_FORWARD_PROTOCOL_UDP\x10\x012\xba\x06\n" +
	"\x0fNetworkerPlugin\x12{\n" +
	"\x1eGetSupportedPortForwardTargets\x12\x16.google.protobuf.Empty\x1aA.omniview.sdk.networker.v1.GetSupportedPortForwardTargetsResponse\x12\x8c\x01\n" +
	"\x15GetPortForwardSession\x128.omniview.sdk.networker.v1.PortForwardSessionByIdRequest\x1a9.omniview.sdk.networker.v1.PortForwardSessionByIdResponse\x12l\n" +
	"\x17ListPortForwardSessions\x12\x16.google.protobuf.Empty\x1a9.omniview.sdk.networker.v1.PortForwardSessionListResponse\x12\x8e\x01\n" +
	"\x17FindPortForwardSessions\x128.omniview.sdk.networker.v1.FindPortForwardSessionRequest\x1a9.omniview.sdk.networker.v1.PortForwardSessionListResponse\x12\x8a\x01\n" +
	"\x17StartPortForwardSession\x124.omniview.sdk.networker.v1.PortForwardSessionOptions\x1a9.omniview.sdk.networker.v1.PortForwardSessionByIdResponse\x12\x8e\x01\n" +
	"\x17ClosePortForwardSession\x128.omniview.sdk.networker.v1.PortForwardSessionByIdRequest\x1a9.omniview.sdk.networker.v1.PortForwardSessionByIdResponseBBZ@github.com/omniviewdev/plugin-sdk/proto/v1/networker;networkerpbb\x06proto3"

var (
	file_proto_v1_networker_networker_proto_rawDescOnce sync.Once
	file_proto_v1_networker_networker_proto_rawDescData []byte
)

func file_proto_v1_networker_networker_proto_rawDescGZIP() []byte {
	file_proto_v1_networker_networker_proto_rawDescOnce.Do(func() {
		file_proto_v1_networker_networker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_networker_networker_proto_rawDesc), len(file_proto_v1_networker_networker_proto_rawDesc)))
	})
	return file_proto_v1_networker_networker_proto_rawDescData
}

var file_proto_v1_networker_networker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v1_networker_networker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_v1_networker_networker_proto_goTypes = []any{
	(PortForwardProtocol)(0),                       // 0: omniview.sdk.networker.v1.PortForwardProtocol
	(PortForwardSession_SessionState)(0),           // 1: omniview.sdk.networker.v1.PortForwardSession.SessionState
	(*PortForwardSession)(nil),                     // 2: omniview.sdk.networker.v1.PortForwardSession
	(*PortForwardResourceConnection)(nil),          // 3: omniview.sdk.networker.v1.PortForwardResourceConnection
	(*PortForwardStaticConnection)(nil),            // 4: omniview.sdk.networker.v1.PortForwardStaticConnection
	(*PortForwardSessionEncryption)(nil),           // 5: omniview.sdk.networker.v1.PortForwardSessionEncryption
	(*PortForwardSessionOptions)(nil),              // 6: omniview.sdk.networker.v1.PortForwardSessionOptions
	(*PortForwardSessionByIdRequest)(nil),          // 7: omniview.sdk.networker.v1.PortForwardSessionByIdRequest
	(*FindPortForwardSessionRequest)(nil),          // 8: omniview.sdk.networker.v1.FindPortForwardSessionRequest
	(*PortForwardSessionByIdResponse)(nil),         // 9: omniview.sdk.networker.v1.PortForwardSessionByIdResponse
	(*PortForwardSessionListResponse)(nil),         // 10: omniview.sdk.networker.v1.PortForwardSessionListResponse
	(*GetSupportedPortForwardTargetsResponse)(nil), // 11: omniview.sdk.networker.v1.GetSupportedPortForwardTargetsResponse
	nil,                           // 12: omniview.sdk.networker.v1.PortForwardSession.LabelsEntry
	nil,                           // 13: omniview.sdk.networker.v1.PortForwardSessionOptions.LabelsEntry
	nil,                           // 14: omniview.sdk.networker.v1.PortForwardSessionOptions.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 16: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_proto_v1_networker_networker_proto_depIdxs = []int32{
	0,  // 0: omniview.sdk.networker.v1.PortForwardSession.protocol:type_name -> omniview.sdk.networker.v1.PortForwardProtocol
	15, // 1: omniview.sdk.networker.v1.PortForwardSession.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: omniview.sdk.networker.v1.PortForwardSession.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: omniview.sdk.networker.v1.PortForwardSession.labels:type_name -> omniview.sdk.networker.v1.PortForwardSession.LabelsEntry
	1,  // 4: omniview.sdk.networker.v1.PortForwardSession.state:type_name -> omniview.sdk.networker.v1.PortForwardSession.SessionState
	5,  // 5: omniview.sdk.networker.v1.PortForwardSession.encryption:type_name -> omniview.sdk.networker.v1.PortForwardSessionEncryption
	3,  // 6: omniview.sdk.networker.v1.PortForwardSession.resource_connection:type_name -> omniview.sdk.networker.v1.PortForwardResourceConnection
	4,  // 7: omniview.sdk.networker.v1.PortForwardSession.static_connection:type_name -> omniview.sdk.networker.v1.PortForwardStaticConnection
	16, // 8: omniview.sdk.networker.v1.PortForwardResourceConnection.resource_data:type_name -> google.protobuf.Struct
	0,  // 9: omniview.sdk.networker.v1.PortForwardSessionOptions.protocol:type_name -> omniview.sdk.networker.v1.PortForwardProtocol
	13, // 10: omniview.sdk.networker.v1.PortForwardSessionOptions.labels:type_name -> omniview.sdk.networker.v1.PortForwardSessionOptions.LabelsEntry
	14, // 11: omniview.sdk.networker.v1.PortForwardSessionOptions.params:type_name -> omniview.sdk.networker.v1.PortForwardSessionOptions.ParamsEntry
	5,  // 12: omniview.sdk.networker.v1.PortForwardSessionOptions.encryption:type_name -> omniview.sdk.networker.v1.PortForwardSessionEncryption
	3,  // 13: omniview.sdk.networker.v1.PortForwardSessionOptions.resource_connection:type_name -> omniview.sdk.networker.v1.PortForwardResourceConnection
	4,  // 14: omniview.sdk.networker.v1.PortForwardSessionOptions.static_connection:type_name -> omniview.sdk.networker.v1.PortForwardStaticConnection
	2,  // 15: omniview.sdk.networker.v1.PortForwardSessionByIdResponse.session:type_name -> omniview.sdk.networker.v1.PortForwardSession
	2,  // 16: omniview.sdk.networker.v1.PortForwardSessionListResponse.sessions:type_name -> omniview.sdk.networker.v1.PortForwardSession
	17, // 17: omniview.sdk.networker.v1.NetworkerPlugin.GetSupportedPortForwardTargets:input_type -> google.protobuf.Empty
	7,  // 18: omniview.sdk.networker.v1.NetworkerPlugin.GetPortForwardSession:input_type -> omniview.sdk.networker.v1.PortForwardSessionByIdRequest
	17, // 19: omniview.sdk.networker.v1.NetworkerPlugin.ListPortForwardSessions:input_type -> google.protobuf.Empty
	8,  // 20: omniview.sdk.networker.v1.NetworkerPlugin.FindPortForwardSessions:input_type -> omniview.sdk.networker.v1.FindPortForwardSessionRequest
	6,  // 21: omniview.sdk.networker.v1.NetworkerPlugin.StartPortForwardSession:input_type -> omniview.sdk.networker.v1.PortForwardSessionOptions
	7,  // 22: omniview.sdk.networker.v1.NetworkerPlugin.ClosePortForwardSession:input_type -> omniview.sdk.networker.v1.PortForwardSessionByIdRequest
	11, // 23: omniview.sdk.networker.v1.NetworkerPlugin.GetSupportedPortForwardTargets:output_type -> omniview.sdk.networker.v1.GetSupportedPortForwardTargetsResponse
	9,  // 24: omniview.sdk.networker.v1.NetworkerPlugin.GetPortForwardSession:output_type -> omniview.sdk.networker.v1.PortForwardSessionByIdResponse
	10, // 25: omniview.sdk.networker.v1.NetworkerPlugin.ListPortForwardSessions:output_type -> omniview.sdk.networker.v1.PortForwardSessionListResponse
	10, // 26: omniview.sdk.networker.v1.NetworkerPlugin.FindPortForwardSessions:output_type -> omniview.sdk.networker.v1.PortForwardSessionListResponse
	9,  // 27: omniview.sdk.networker.v1.NetworkerPlugin.StartPortForwardSession:output_type -> omniview.sdk.networker.v1.PortForwardSessionByIdResponse
	9,  // 28: omniview.sdk.networker.v1.NetworkerPlugin.ClosePortForwardSession:output_type -> omniview.sdk.networker.v1.PortForwardSessionByIdResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_v1_networker_networker_proto_init() }
func file_proto_v1_networker_networker_proto_init() {
	if File_proto_v1_networker_networker_proto != nil {
		return
	}
	file_proto_v1_networker_networker_proto_msgTypes[0].OneofWrappers = []any{
		(*PortForwardSession_ResourceConnection)(nil),
		(*PortForwardSession_StaticConnection)(nil),
	}
	file_proto_v1_networker_networker_proto_msgTypes[4].OneofWrappers = []any{
		(*PortForwardSessionOptions_ResourceConnection)(nil),
		(*PortForwardSessionOptions_StaticConnection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_networker_networker_proto_rawDesc), len(file_proto_v1_networker_networker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_networker_networker_proto_goTypes,
		DependencyIndexes: file_proto_v1_networker_networker_proto_depIdxs,
		EnumInfos:         file_proto_v1_networker_networker_proto_enumTypes,
		MessageInfos:      file_proto_v1_networker_networker_proto_msgTypes,
	}.Build()
	File_proto_v1_networker_networker_proto = out.File
	file_proto_v1_networker_networker_proto_goTypes = nil
	file_proto_v1_networker_networker_proto_depIdxs = nil
}
